### PR TITLE
Media Library: Add button to select all items, fixes #6518

### LINKED ISSUE #6518: Media Library: Add button to select all items
There is currently no way to select all images from a folder in the Media Library. If you want them all, you have to individually ctrl+click every image then click the "select" button. I'm proposing adding a button next to the "Select" button called "Hightlight All" which when clicked, loops through all images in the current displayed folder and marks them as selected (green square). 

I'm proposing the phrase "Highlight All" instead of "Select All" because the current "Select" button confirms your choice and closes the Media Library dialog, so this would avoid confusion. This new button would not close the dialog, so it would allow you to navigate to another folder and "Highlight All" from that folder as well, adding to the selection list on the right hand side.

### PR DESCRIPTION
**Pull request by MobesE46**
Fixes #6518 - New button to select all images in media library folder.

Supersedes PR #6519 to target 1.10.x

### CODE REVIEW

**Comment by sebastienros** [comment]
GTG once someone has confirmed it works and doesn't break existing features.

**Comment by MobesE46** [comment]
Here's the new button:
image

After clicking button:
image

**Comment by sebastienros** [comment]
What I see from the code is that `Select` will actually close the window and select items, while `Select All` will just highlight the items. Is that intentional? It would mean to actually select all items you need to click `Select All`, then `Select`. So maybe this button should actually be in the toolbar, so that there is no confusion with the `Select` action of the picker.

**Comment by MobesE46** [comment]
Ok, I moved the button to the Toolbar

image

**Comment by BenedekFarkas** [comment]
Confirmed as working, but I'll push some changes/improvements.

**Pull request merged**
