### PR TITLE
Define constants for maximum username/email length

### PR DESCRIPTION
**Pull request by MpDzik**

### CODE REVIEW

**Comment by Jetski5822** [comment]
Are we sure the Email Length should be validated interms of a total length? should we not validate the domain length and then the total length?

**Comment by Jetski5822** [comment]
http://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

**Comment by MpDzik** [comment]
I'm not sure. I did this refactoring because I am importing users into Orchard from external data sources and I need to validate the input data. I want to duplicate Orchard's validation logic, but without hardcoding magic numbers. That's why I needed to introduce these constants.

**Comment by pszmyd** [comment]
I guess we already have a 255-char limit already because of the default nvarchar length used.

**Pull request merged**
