### PR TITLE
Resolving typos in 3 modules (#6724)

### LINKED ISSUE #6724: Typos in different modules
If you want to make your first pull request, here are some typos that need to be fixed.
Find the corresponding strings and fix them.

Your haven't specified a taxonomy for {0} : Your => You
The default value for the field. It must be a number, and if not it will not shown. : missing 'be' before shown
Select wether you want to import the selected recipe : wether => whether

### PR DESCRIPTION
**Pull request by davidelstone**
fixes #6724. 

Simple amendments to resolve the typos in 3 modules - I've made the corrections as described in the issue. Thanks for including the first-timers-only label!

### CODE REVIEW

**Comment by agriffard** [comment]
Thank you for your contribution. 
Pull requests are often merged on Thursday, during the weekly bug triage meeting.

**Comment by sebastienros** [comment]
Needs to target 1.10.x

**Comment by davidelstone** [comment]
@sebastienros My apologies! Quick question: I naively based the changes on master, so will you need the changes rebasing to 1.10.x, or is it OK to simply close this PR & create another from the same branch targeting 1.10.x?

**Comment by sebastienros** [comment]
Please create a new PR targeting 1.10.x, thanks.

**Pull request closed without merging**
