### PR TITLE
#6733: Content item of Comment should first be 'Created' before being passed into `UpdateEditor`

### PR DESCRIPTION
**Pull request by qingfx**
Orchard.Blogs.BlogPostAdminController.CreatePOST(int blogId, bool publish) is a good example on how to implement content item creation.

CommentController.Create(...) should ContentManager.Create the CommentPart first, only then use ContentManager.UpdateEditor(...) to update part and validate updated part. After this:
- If everything is correct, all DB changes will be saved upon request finishes. -OR-
- If something goes wrong, say ModelState.IsValid == false, cancel the DB transaction via Services.TransactionManager.Cancel()

### CODE REVIEW

**Comment by Skrypt** [comment]
Could you point on the issues # that it will fix.

**Comment by jtkech** [comment]
With @560889223 and @Skrypt we tried to allow the pattern "create after update" but we had drawbacks with handlers / drivers that create repository record that rely on the content item.

If the driver / handler check if it's a new item (not already created), no exception but the field is not persisted. So we needed to add a 2nd UpdateEditor as suggested in #6534.

But if the driver / handler doesn't check if it's a new item, there are exceptions. So we needed to use again "create before update". It can be fixed at the driver / handler level but we thought that we can't rely on this.

Here, the issue was with the CommentController and an AuditTrail handler. **And i can confirm that this PR fixes this issue**.

Best.

**Comment by sebastienros** [comment]
But calling Create and cancelling the transaction will create transaction logs. Please take a look at the previous change to this class that fixed another issue so that it doesn't conflict with it, or we need to find a compromise.

**Comment by jtkech** [comment]
@sebastienros 

You're right it was since this commit 874bd7d to fixes this work item [19304](https://orchard.codeplex.com/workitem/19304). I'll take a look.

**Comment by 560889223** [comment]
@sebastienros 

In that case, work item 19304 sounds not unique to `Comment`; many content items that are recreated before model validation could have similar issues. The problem is that today's `ContentManager.Create` is not being used in the same sense as the user perceived. It's more like creating a placeholder for the content item-to-insert-into-database. To align `ContentManager.Create` with what the user perceives, it seems to me that we have to draw a clear line between validation and creation. The event broadcasting and the work of creating `ContentItemRecord`/`ContentItemVersionRecord` needs to be separated.

I'm suggesting the following:

1. Today's `UpdateEditor` will be renamed to `UpdateEditorImpl` and no longer broadcasting events `Updating`/`Updated`.
2. Today's `Create` will be renamed to `CreateImpl` and no longer broadcasting events `Creating`/`Created`.
3. To respond a user's request to create a content item, one should:
  1. `ContentManager.Validate`, think it as a **dry-run** of `UpdateEditorImpl` that does checks without updating content item. This gives controller/service a chance to fail creation without appending noises to DB transaction logs.
  2. `ContentManager.Create`
    1. Calls `CreateImpl`.
    2. Broadcast `Creating` events with the new `Created` content item. 
    3. Calls `UpdateEditorImpl`.
    4. Broadcast `Created` events with the populated content item.
4.  To respond a user's request to update an existing content item, one should:
  1. `ContentManager.Validate`, think it as a **dry-run** of `UpdateEditorImpl` that does checks without updating content item. This gives controller/service a chance to fail creation without appending noises to DB transaction logs.
  2. `ContentManager.Update`
    1. Broadcast `Updating` events with the existing content item. 
    2. Calls `UpdateEditorImpl`.
    3. Broadcast `Updated` events with the updated content item.

**Comment by jtkech** [comment]
@sebastienros @560889223.

The work item was about using Orchard.Rules (now deprecated) to send an e-mail on comment publication. That's why the create was moved after `UpdateEditor()` and model checking in 874bd7d.

The comments controller uses `Services.ContentManager.Create()` with no `VersionOptions`, so `Published` is used. So, the create action do a create and publish, so the publish event is triggered.

**Compromise 1**

One compromise that doesn't conflict with the work item is to do a create with a `Draft` option.

    Services.ContentManager.Create(comment, VersionOptions.Draft); // no publish event here
    var editorShape = Services.ContentManager.UpdateEditor(comment, this);
    ...
    ...
        if (ModelState.IsValid) {
            Services.ContentManager.Publish(comment.ContentItem); // publish event here

But if you are using, e.g in a workflow, a comment creation event, you may have to swap to a publish one.

**Compromise 2**

As you, i would prefer to use the "create after update" pattern to preserve transaction logs and @560889223 suggestion with a new `ContentManager.Validate` implementation looks very good.

Currently, to use this pattern we have to fix handlers / drivers that do actions relying on a created item but without checking it. Then, we also have to re-call `UpdateEditor()` after the effective create.

So, here we would have to update `GlobalContentHandler`, the one that was failing in this issue. In the `Updating / Updated` events, if it's a new item (not created) then don't record an audit trail event.

For doing this, we can use this new content extension:

    public static bool IsNew(this IContent content) {
        return content.ContentItem.VersionRecord == null;
    }

And in `CommentController` do a 2nd `UpdateEditor()`:

    var comment = Services.ContentManager.New<CommentPart>("Comment");
    // The 1st update simulate the validation step but some drivers / handlers,
    // in their update events need to check if it's a new item before doing some actions
    var editorShape = Services.ContentManager.UpdateEditor(comment, this);
    ...
    ...
        if (ModelState.IsValid) {
            Services.ContentManager.Create(comment, VersionOptions.Draft); // create without publish
            // 2nd update events where actions relying on a created item can be done
            Services.ContentManager.UpdateEditor(comment, this);
            Services.ContentManager.Publish(comment.ContentItem); // publish events only here
            ...

Best.

**Comment by jtkech** [comment]
@sebastienros @560889223 

So, specifically for comments (many items, spams ...), here the best compromise i've found and tested.

In `CommentController.cs`:

            var comment = Services.ContentManager.New<CommentPart>("Comment");
            var editorShape = Services.ContentManager.UpdateEditor(comment, this);
            ...
            ...
            if (ModelState.IsValid) {
                Services.ContentManager.Create(comment, VersionOptions.Draft);
                Services.ContentManager.UpdateEditor(comment, this);
                Services.ContentManager.Publish(comment.ContentItem);
                ...

In `GlobalContentHandler.cs` in both `Updating()` and `Updated` methods:

            var contentItem = context.ContentItem;

            if (contentItem.IsNew())
                return;

At the end of `ContentExtensions.cs`: (will be there with #6720 on default values)

        public static bool IsNew(this IContent content) {
            return content.ContentItem.VersionRecord == null;
        }

Finally, if there are already bad audit trail records created before this fix, to prevent admin audit trail views from failing, in `DiffGramAnalyzer`:

    // Replace this line with the following
    //var index = match == null || isAttributeChange ? default(int?) : Int32.Parse(match) - 1;

    int matchInt;
    var index = match == null || isAttributeChange || !Int32.TryParse(match, out matchInt)
        ? default(int?) : matchInt - 1;


Best.

**Comment by BenedekFarkas** [comment]
[JT's suggested changes](#issuecomment-211128847) were applied on dev with #6891.

**Pull request closed without merging**
