### PR TITLE
Live preview feature (Orchard.ContentPreview back-port; Lombiq Technologies: WESD-1)

### PR DESCRIPTION
**Pull request by Piedone**
A back-port from the Orchard Core Orchard.ContentPreview module with the live preview feature. It's as close to the original module as possible. Done by @I3undy.

- The module is intended work exactly as it works in Orchard Core.
- Made the module compatible with the TinyMCE editor and the Layout Editor. Apart from these no enhancements or functionality changes are made to the module.

### CODE REVIEW

**Comment by sebastienros** [comment]
Awesome!!!! 
I remember a problem that was making it hard to do in O1, so please check that. When we create a new content item (.New) then a record is created in the database, maybe a new version actually, so we need to check every Render() call is not creating a new one. Or if it does then that it's not an issue.

**Comment by Piedone** [comment]
Hmm, @I3undy please chime in but I don't think a persistent record is created on `New()` (record objects are, but they won't have an auto-increment `Id` assigned either). In any case we didn't notice any performance or other issues.

**Comment by Piedone** [comment]
I just checked and it's not creating new versions during the preview, i.e. no new records e.g. in the `Orchard_Framework_ContentItemVersionRecord` table.

**Comment by sebastienros** [comment]
Will we get a demo on Tuesday?

**Comment by Piedone** [comment]
Yes!

**Pull request merged**
