### PR TITLE
fix #6374 for 1.10

### LINKED ISSUE #6374: jQueryUI_Widgets does not exist in 1.10 now
exception for call 
Script.Require("jQueryUI_Widgets");

### PR DESCRIPTION
**Pull request by infofromca**
fix #6374 for 1.10

### CODE REVIEW

**Comment by sebastienros** [comment]
I don't think this is the correct fix. We should declare the widgets resource pointing to jQueryUI this way anyone using it won't be broken.

**Comment by sebastienros** [comment]
@DanielStolt

**Comment by DanielStolt** [comment]
@sebastienros I disagree, this fix is correct. The resource name "jQueryUI_Widgets" no longer exists. The old one (which we kept for compat) is named "jQueryUI_Widget" (singular). I did a few similar fixes like this one yesterday, can't figure out why I missed these two.

**Comment by sebastienros** [comment]
Ok, I get it now. I thought this was about a resource removed in 1.10.

**Pull request merged**
