### PR TITLE
Block requests to tenant while it's being restarted

### PR DESCRIPTION
**Pull request by Piedone**
See #4569. The branch name is different because this was started before the move to GitHub.

### CODE REVIEW

**Comment by sebastienros** [comment]
For the ones signing-off, please ensure that restarting one tenant doesn't block the other ones. For instance enabling a feature doesn't stop handling requests for other tenants.

**Comment by sebastienros** [comment]
Please squash the commits once you get the sign-off.

**Comment by Piedone** [comment]
Yes, for tenants not blocking others is there the the named locking mechanism.

Since these commits are already pushed (to the Orchard repo) squashing them would rewrite history, requiring a force push. I wouldn't want to do that.

**Comment by sebastienros** [comment]
> Since these commits are already pushed

Then either your PR is wrong or it has an issue ;)

**Comment by sebastienros** [comment]
It seems to be an old branch, why don't you soft reset to dev then create a single commit?

**Comment by Piedone** [comment]
As I said yes, it is an old branch. Hence it's already there it won't be nicer by adding even more commits: because again since these are already pushed rebasing this as one commit on top of dev would still be history rewriting, meaning that if anybody having a prior clone of the Orchard repo (because this is not in a fork) does a push all branches then it'd re-appear for example.

**Comment by sebastienros** [comment]
This is fine, it's a working branch that you own, feel free to break it as much as you want.

**Comment by sebastienros** [comment]
dev or 1.10.x ? (don't forget to squash)

**Comment by Piedone** [comment]
Created a new PR, now to 1.10.x.

**Pull request closed without merging**
