### PR TITLE
[Fixes #7195] Admin Theme - BodyPart TinyMCE Editor - New Font Size

### LINKED ISSUE #7195: Admin Theme - BodyPart TinyMCE Editor - New Font Size
Should have new font size to match modern screens better:

image

This is just a CSS admin-side setting in TinyMCE and doesn't affect the output on peoples sites. It's just how paragraph is formatted in the editor.

### PR DESCRIPTION
**Pull request by rtpHarry**
[Fixes #7195] Admin Theme - BodyPart TinyMCE Editor - New Font Size

### CODE REVIEW

**Comment by sfmskywalker** [comment]
I assume there was no unminified source available?

**Comment by rtpHarry** [comment]
no the tinymce module is a bit messy, it modifies files bundled in with the core tinymce script, this is just a clone of the default skin which comes minified.

**Comment by sfmskywalker** [comment]
Ok

**Comment by Skrypt** [comment]
you guys are like issue fixers robots 👍

**Comment by sfmskywalker** [comment]
:)

**Comment by rtpHarry** [comment]
I seem to be making as many as a I close though! The neverending story...

**Comment by sfmskywalker** [comment]
Keep it up. It will end!

**Comment by Skrypt** [comment]
Problem is that I have absolutely no time to help 👎 
You guys are saving my life 😄

**Comment by sfmskywalker** [comment]
This is how a team works!

**Comment by rtpHarry** [comment]
I am about done for the day though, I'm running a half-marathon tomorrow morning so I need to prep and get my beauty sleep 💤 

I've got through a fair amount but created many more, and even more that are just notes at the moment waiting to be turned into issues. 

I have started [working on some docs](https://github.com/OrchardCMS/OrchardDoc/issues/311) for the new theme as well.

**Comment by sfmskywalker** [comment]
Thanks Matthew. Good luck with the marathon!

**Comment by rtpHarry** [comment]
I survived :) 1hr 49mins

**Comment by sfmskywalker** [comment]
Well done :)

**Pull request merged**
