### PR TITLE
Fix for issue #5219

### PR DESCRIPTION
**Pull request by giannik**
will need to bump the version numbers from 1.8.1.0  to 1.9 when released.

### CODE REVIEW

**Comment by sfmskywalker** [comment]
I think this should go into the dev branch, since the master branch will not contain the changes made to the project references - that was done in 1.x.

**Comment by sfmskywalker** [comment]
It looks like we can add assembly references without specifying a version number. In my test, this works:

```xml
<add assembly="Orchard.Framework"/>
<add assembly="Orchard.Core"/>
```

**Comment by giannik** [comment]
yes, removing version number  works for me too. 
Shall i make a new pull request in 1.x or will you handle it ?

**Comment by sfmskywalker** [comment]
That'd be great. Thanks!

**Comment by giannik** [comment]
done.
new pull request #5232

**Pull request closed without merging**
