### PR TITLE
- Added attachments logic

### PR DESCRIPTION
**Pull request by HermesSbicego-Laser**
Support for attachments via IMessageChannel #6196

### CODE REVIEW

**Comment by sebastienros** [comment]
Can someone else verify the feature works as expected?

**Comment by HermesSbicego-Laser** [comment]
@sebastienros 
We have some custom modules using it, but it is self-referential.
What I could do is changing EmailAdminController.TestSettings in order to attach "/Orchard.Web/Media/OrchardLogo.png" as attachement to the test email.
It could be sufficient?

**Comment by sebastienros** [comment]
Will force-accept  if noone has tried it until 11/10

**Comment by HermesSbicego-Laser** [comment]
can be merged then?

**Comment by HermesSbicego-Laser** [comment]
Now, should be ready for merge in 1.10.x

**Comment by Xceno** [comment]
I just saw this issue. Thanks for implementing this @HermesSbicego-Laser!
I've tested your changes locally and they've worked very well.

**Comment by HermesSbicego-Laser** [comment]
Thank you @Xceno ! Yes, it's a small enhancement but useful...

**Pull request merged**
