### PR TITLE
Query database schema instead of Nhibernate configuration to get tenant tables list

### PR DESCRIPTION
**Pull request by mdameer**
Issue #7885

### CODE REVIEW

**Comment by sebastienros** [comment]
Shouldn't it use table prefix somewhere?

**Comment by mdameer** [comment]
@sebastienros, this code will read table names from database schema, so the prefix will be included with table names like the previous implementation, also the following line will remove the prefix before run the drop command through SchemaBuilder: `schemaBuilder.DropTable(schemaBuilder.RemoveDataTablePrefix(tableName));`

**Comment by sebastienros** [comment]
This code reads all the tables, a database can contain tables for many tenants, partitioned with a prefix, lie `Site1_ContentItemRecord`, `Site2_ContentItemRecord`, ... 
Then it removes as many chars as the prefix has, so it can even create wrong table names, and if you are deleting a tenant without prefix, it will delete all the tables, even if they have prefixes.

**Comment by sebastienros** [comment]
So this code only works if you have a single tenant in the db.

**Pull request merged**
