### PR TITLE
#6064 allow placing of menu item on creating or editing page

### PR DESCRIPTION
**Pull request by mattcowen**
Apologies for the formatting issues.

### CODE REVIEW

**Comment by Piedone** [comment]
Line endings in some files were fixed in the Orchard source, that's why this PR now has merge conflicts.

Please sync your fork with the Orchard repo and merge the target branch of this PR into your branch (for a guide see: https://help.github.com/articles/syncing-a-fork/ or alternatively if you use GitExtensions you can simply add https://github.com/OrchardCMS/Orchard.git under Repository/Remote repositories, do a fetch all and then merge the target branch into your branch).

If you have files appearing changed in your working directory that you didn't change but were actually touched by git to normalize line endings then you don't need to commit those (these were also fixed): clear the contents of the .gitattributes file in the repository root or remove the file, then do the merge. The changed files won't appear now (.gitattributes instructs git to care about line endings) but please don't commit the .gitattributes change (you can simply reset that change).

There shouldn't be too many merge conflicts and most of those should be resolved automatically by the merge tool (in GitExt hit Start merge tool and it will be able to do the merges).

Sorry about the inconvenience. On the upside this leftover from the hg to git conversion is now gone :-).

If you need further help just ping me here.

**Comment by sebastienros** [comment]
What was the result of our discussion about using custom links?

Please fix the merge issue.

**Comment by BenedekFarkas** [comment]
@sebastienros the issue is closed by the author, but this PR is not. The discussion concluded that we should get rid of MenuPart due to its potential performance impact or refactor it to use content item URLs.
The problem with the latter I think is that at the moment this functionality is in Core, while custom URLs are provided Orchard.Autoroute. Without that, we could use the built-in display route (/Contents/Item/Display/{id}). So maybe we could refactor and move MenuPart to AutorouteMenuPart?

**Comment by sebastienros** [comment]
> move MenuPart to AutorouteMenuPart

It would have the same performance issue.

**Comment by BenedekFarkas** [comment]
I think we misunderstood this, because this issue is about MenuPart + MenuItem(Part), but the one that has Select N+1 performance problems is ContentMenuItem (in the ContentPicker module).

So it's actually ContentMenuItem that we should consider removing or refactoring, but this a different matter.

**Comment by BenedekFarkas** [comment]
The corresponding issue was closed as "wontfix" (sort of), so I'm closing this PR as we are planning to make some changes to Navigation soon. The current course of action is to remove ContentMenuItem (and MenuPart with it), but we might add a slightly different functionality that uses CustomLink (and maybe updates automatically to adapt to Autoroute Path changes) to mitigate SELECT N+1 issues.

**Pull request closed without merging**
