### PR TITLE
Fires Updating and Updated events when menu items are re-ordered

### LINKED ISSUE #6005: Re-ordering menu items within a menu does not trigger the Updating and Updated events for each MenuPart
Because the properties on this part is updated by the Navigation Admin Controller (as opposed to a driver) then these events are not raised.

Suggest injecting the handlers into the controller and invoking those events of the position property changes on the part.

### PR DESCRIPTION
**Pull request by paynecrl97**
Fixes #6005

### CODE REVIEW

**Comment by sebastienros** [comment]
Shouldn't it be the same from the Menu content item BTW?

**Comment by sfmskywalker** [comment]
@sebastienros Are you proposing that whenever a `Menu` content item is deleted, the `Updating` and `Updated` events on its menu items should be invoked as well? I think that would make sense.

**Comment by paynecrl97** [comment]
Agree. I can do that. Leave it with me.

**Comment by sebastienros** [comment]
No I meant calling update on the Menu, which is what is already done, my bad.

**Pull request merged**
