### PR TITLE
Use Localized Strings to decorate View Models (LocalizedDisplayName attribute)

### PR DESCRIPTION
**Pull request by harmony7**
Created a pluggable ModelMetadataProvider framework and a provider
implementation allowing LocalizedDisplayName attributes to be placed on
view model properties

### CODE REVIEW

**Comment by harmony7** [comment]
I created this because I wanted to be able to use data annotations on my view models and LabelFor to create my UIs, but I also wanted the labels to be localized strings.

We see a lot of this in Orchard:

View model:

    public string Property { get; set; }

Template:

    @Html.LabelFor(m => m. Property, T("Description"))

But this will allow this:

View model:

    [LocalizedDisplayName("Description")]
    public string Property { get; set; }

Template:

    @Html.LabelFor(m => m. Property)


This commit includes the following:

`IModelMetadataProvider` - an interface that a model metadata provider can implement.

`DefaultModelMetadataProvider` - an implementation of the aforementioned interface that is based on the DataAnnotationsModelMetadataProvider (the default used by ASP.NET MVC) but also allows `IModelMetadataProcessor` implementations to modify the results of Metadata retrieval.

`ModelMetadataProviderProxy` - since ModelMetadataProvider is a singleton in ASP.NET MVC and is shared across the entire app, this proxy was created to delegate calls to its methods to the appropriate `IModelMetadataProvider` implementation, and falls back to the default ModelMetadataProvider if the work context could not be resolved. This Proxy has been wired in via `OrchardStarter.cs`.

`LocalizedModelMetadataProcessor` - kicks in as an `IModelMetadataProcessor` implementation. If the model property is decorated with `LocalizedDisplayNameAttribute`, then the value is determined and used as the text hint for localization.

`LocalizedDisplayNameAttribute` inherits `DisplayNameAttribute`, so if `DefaultModelMetadataProvider` isn't able to do its work, the default model metadata provider will allow the text hint to be used directly as the output.

**Comment by harmony7** [comment]
Committed a typo fix.

**Comment by sebastienros** [comment]
What about his kind of feature:
https://github.com/OrchardCMS/Orchard/issues/5510

**Comment by harmony7** [comment]
@sebastienros I'm sorry I don't think I understand.

My suggested feature is to allow standard ASP.NET MVC HtmlHelper.LabelFor() to resolve LocalizedString objects.

I'm not suggesting a way to manage the actual translated strings (PO file, DB, etc) as #5510 is discussing.

**Comment by harmony7** [comment]
I changed the name of this to describe the purpose more than the implementation

**Comment by rtpHarry** [comment]
Oh, I thought that this was actually already happening here:

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Mvc/DataAnnotations/LocalizedModelValidatorProvider.cs#L57

But I just set a breakpoint and it isn't actually anything to do with it is it? I'm pretty sure I put this into the Orchard Docs recently.

**Comment by rtpHarry** [comment]
It's a bit long winded but you can localize your `[DisplayName]` and keep it DRY with this:

    @Html.LabelFor(model => model.IsOnSale, T(Html.DisplayNameFor(model => model.IsOnSale).ToHtmlString()))

**Comment by sebastienros** [comment]
I too think it's already implemented the way @rtpHarry is mentioning, I also remember when I implemented it ... Could it be broken? Or is it that you are missing the correct "context" file for localization.

**Comment by rtpHarry** [comment]
@sebastienros after I first saw this thread I put a breakpoint on that code on `LocalizedModelValidatorProvider.cs` and ran it on a simple demo module I was working on. 

It just had a simple model with a `[DisplayName]` attribute but the `LocalizedModelValidatorProvider.cs` code wasn't hit.

I don't know if this means it never runs it or if it doesn't run it for the default localization?

**Comment by sebastienros** [comment]
Related: https://github.com/OrchardCMS/Orchard/issues/5948

**Comment by Piedone** [comment]
Line endings in some files were fixed in the Orchard source, that's why this PR now has merge conflicts.

Please sync your fork with the Orchard repo and merge the target branch of this PR into your branch (for a guide see: https://help.github.com/articles/syncing-a-fork/ or alternatively if you use GitExtensions you can simply add https://github.com/OrchardCMS/Orchard.git under Repository/Remote repositories, do a fetch all and then merge the target branch into your branch).

If you have files appearing changed in your working directory that you didn't change but were actually touched by git to normalize line endings then you don't need to commit those (these were also fixed): clear the contents of the .gitattributes file in the repository root or remove the file, then do the merge. The changed files won't appear now (.gitattributes instructs git to care about line endings) but please don't commit the .gitattributes change (you can simply reset that change).

There shouldn't be too many merge conflicts and most of those should be resolved automatically by the merge tool (in GitExt hit Start merge tool and it will be able to do the merges).

Sorry about the inconvenience. On the upside this leftover from the hg to git conversion is now gone :-).

If you need further help just ping me here.

**Comment by harmony7** [comment]
closing this

**Pull request closed without merging**
