### PR TITLE
Added a filter for projections over StringFields that allows returnin…

### LINKED ISSUE #8225: Return all items by projection in ContainsAll if provided value is empty
Need a filter for projections over StringFields that allows returning all items when the provided value is empty.
Like the filter ContainsAnyIfProvided i need a ContainsAllIfProvided filter
I will make a pr to do this.

### PR DESCRIPTION
**Pull request by LorenzoFrediani-Laser**
Added a filter for projections over StringFields that allows returning all items when the provided value is empty.

Add a ContainsAllifProvided filter to get All items if no "filter" is selected
this solve the #8225 issue

### CODE REVIEW

**Comment by BenedekFarkas** [comment]
I see this is a follow-up to #8213. Actually, I think this should be a completely separate option for all types of data, not just strings: A common checkbox for all FieldTypeEditors that (when checked/enabled) does not run the filter if the provided value is empty, which can be quite common if you use a Token (e.g. filter by a query string parameter). I did something similar in [Lombiq.Projections](https://github.com/Lombiq/Lombiq-Projections) (NullSafeStringFieldTypeEditor), but it only applies to strings and is a separate filter.
To have this generalized could be a nice improvement to this feature, what do you think?

@LorenzoFrediani-Laser if I understand correctly, this would also cover your case, because ContainsAll and ContainsAny already exists, so you'd have to just update the filters with this option enabled.

**Comment by MatteoPiovanelli** [comment]
@BenedekFarkas I think what you are proposing makes sense for dev perhaps? I would merge this PR here in 1.10.x

**Comment by BenedekFarkas** [comment]
That only works with those two specific cases. What I'm suggesting above is a simple, generic solution that can be applied to any filter (and when applied to a filter, it works regardless of what the rest of its configuration is).
I'll give it try and see if that indeed works for you too as expected.

**Comment by BenedekFarkas** [comment]
Please see #8781.

**Comment by BenedekFarkas** [comment]
Closing this as #8781 covers the desired functionality: Use the `ContainsAll` value for `Operator` and the new checkbox (`IgnoreFilterIfValueIsEmpty`).

**Pull request closed without merging**
