### PR TITLE
Refactoring Content Management for async operation, fixes #8212

### LINKED ISSUE #8212: Refactoring Content Management for async operation
This is an issue created for an already submitted PR that aims to convert Content Management (and everything that uses it) for async operation: #5324

### PR DESCRIPTION
**Pull request by aonweb**
Issue #8212 

This is a modification to the Content Manger, Content Handler, Content Part Driver pipeline to allow asynchronous content drivers and content shape results.

We've been using this basic code on the amctheatres.com website, which makes heavy use of ContentPartDrivers with content sourced from http web service calls on the site for a while now.

### CODE REVIEW

**Comment by aonweb** [comment]
I removed the dependency on AsyncBridge..

**Comment by sebastienros** [comment]
If you fix the merge issues I will do some tests on my side. The cache module should be disabled to analyze the actual impact, and parallel requests should be used. I personally use Apache Bench for this.

**Comment by aonweb** [comment]
Will do. I was sending a no-cache header on the tests, which should bypass cache unless the profiling build changes the CacheSettings.IgnoreNoCache, but they weren't in parallel. I can set something up using Apache Bench as well.

**Comment by Piedone** [comment]
Line endings in some files were fixed in the Orchard source, that's why this PR now has merge conflicts.

Please sync your fork with the Orchard repo and merge the target branch of this PR into your branch (for a guide see: https://help.github.com/articles/syncing-a-fork/ or alternatively if you use GitExtensions you can simply add https://github.com/OrchardCMS/Orchard.git under Repository/Remote repositories, do a fetch all and then merge the target branch into your branch).

If you have files appearing changed in your working directory that you didn't change but were actually touched by git to normalize line endings then you don't need to commit those (these were also fixed): clear the contents of the .gitattributes file in the repository root or remove the file, then do the merge. The changed files won't appear now (.gitattributes instructs git to care about line endings) but please don't commit the .gitattributes change (you can simply reset that change).

There shouldn't be too many merge conflicts and most of those should be resolved automatically by the merge tool (in GitExt hit Start merge tool and it will be able to do the merges).

Sorry about the inconvenience. On the upside this leftover from the hg to git conversion is now gone :-).

If you need further help just ping me here.

**Comment by BenedekFarkas** [comment]
This is a bummer, but we left this PR here for quite a long time. At this time, we've concluded that due to the large number of breaking changes and the fact that there was no substantial performance benefit, we'll close this PR.

**Pull request closed without merging**
