### PR TITLE
Replace lib with nuget

### PR DESCRIPTION
**Pull request by gcsuk**
RE: Issue https://github.com/OrchardCMS/Orchard/issues/6148 replacing PR https://github.com/OrchardCMS/Orchard/pull/6149 (whose branch I accidentally ruined)

This PR updates all assembly references from the lib folder to NuGet, where a NuGet version is available, and references new custom Orchard nuget feed for the remainder.

Because of the amount of changes, I recommend reviewers pull the branch as GitHub compare is useless.

Where possible, the exact same version has been used from NuGet.

The following packages have no version changes:

Autofac
Azure
Castle
DotNetZip
ImageResizer
IronRuby
Log4Net - Package 2.0.3 contains assembly 1.2.13 (unchanged)
Lucene
MVC
Newtonsoft.Json
NHibernate
npgsql
Owin
Redis
Specflow
XMLDiffPatch
WebApi

The following references are different, but no further than a Minor version change. This is because the lib versions are old so NuGet doesn’t have them available

HtmlAgilityPack: 1.3.9.1 >>> 1.4.9.0
Moq: 4.0.812 >>> 4.0.10827
MySql: 6.5.4.0 >>> 6.7.9.0
NUnit: 2.5.2.9222 >>> 2.5.10.11092

The following assemblies have been added to a dedicated Orchard NuGet feed:

FluentPath
MSTranslitTools
NuGet
Azure.ServiceRuntime
Azure.Diagnostics

The following are being left in lib:

MSBuild
MSDeploy
NHibernate.Linq (custom build)
SqlCe (still to do, working on it
TypeScript
WCAT

The following lib folders have been removed as they are no longer needed:

HistoryJs
HtmlShim
jQuery
jQuery UI
jQueryUtils

### CODE REVIEW

**Comment by Piedone** [comment]
Could you repeat the open questions here please so others can chime in?

**Comment by gcsuk** [comment]
@Piedone The questions on the old PR were for commits that I brought in accidentally (hence ruining the other branch), I think that everything has been addressed now apart from the checklist on the issue which is as follows:

* Finish the migration of the other packages, by adding them to Nuget ***[In progress]***
* Test the deployment strategies

For this PR, I have the following lib folders left to do, and would appreciate any advice/help with them:

* **msdeploy, **wcat*** and **typescript** - Are these needed? I am not sure how to go about adding them to the solution, as they are unreferenced executables/scripts. Shall I leave them in the lib folder?
* **nhibernate.linq** - This needs a C# file to be in the folder with the assembly, I don't know how to get NuGet to do this.
* **sqlce** - I am struggling to put together a working NuGet package for this one, as its structure is complex and I am unsure exactly what needs to go where.

@sfmskywalker and myself have the credentials for the new OrchardCMS NuGet feed. Ping me if you need them.

Any help appreciated.

**Comment by sfmskywalker** [comment]
Could we leave those 3 lib folders for the time being and get the rest in? @sebastienros ?

**Comment by gcsuk** [comment]
:+1: from me

**Comment by Piedone** [comment]
Good idea, why move those. Is there any reason we want to have *everything* as NuGet, even for those libs where we need to create the package for them?

**Comment by gcsuk** [comment]
I think the ones I have done, such as the Azure DLLs, should be there as it keeps everything in one place and all references will point to the packages folder, but these remaining ones are loose files so I think they should stay where they are

**Comment by sfmskywalker** [comment]
I think we should take this PR as it is, and then we can always reiterate over the remaining lib folders at a later time. Unless anyone objects?

**Comment by Piedone** [comment]
This change has huge impact so I'd rather wait for more comments if anyone has.

**Comment by gcsuk** [comment]
There was a lengthy discussion about it, I think everyone is just waiting for it to be reviewed and go in.

**Comment by Piedone** [comment]
It was lengthy as text but has only gone on for two weeks. While I agree with these changes I don't want some potential deal breaker counter-argument not to be heard due to such a short time window not being enough for someone to notice the discussion.

I tweeted this out, @sebastienros could you also do this from the Orchard account?

**Comment by sebastienros** [comment]
Done

**Comment by Piedone** [comment]
Thank you.

**Comment by urbanit** [comment]
Sounds good. It would be better if the guideline is the same for modules...

**Comment by CSurieux** [comment]
I recently used a Google Nuget package (funnyy no ?) in a module and I get lot of problems with bad version of assmblies. Visual Studio fixes them by modifying the modulee web.config. But not the Orchard.Web web.config wich is the only one necessary when running. And I have to fix it by hand. Isn't there a potential problem, each module having its own packages independently ?

**Comment by Piedone** [comment]
@CSurieux yes, that will be an issue unless your module project is references by Orchard.Web which you shouldn't have to do.

@urbanit the issue I see here is that you can't utilize NuGet if you want to distribute your module in a way that it can be installed from the Gallery, since that path doesn't have NuGet support (imagine somebody using the Orchard web package, then installing the module from under the admin). So if your module is only used by developers in VS then you can already utilize NuGet, otherwise you won't be able to even after this change.

**Comment by urbanit** [comment]
@Piedone so, it is module development vs module install? Of course, first priority should web admins..

**Comment by Piedone** [comment]
@urbanit if by that you mean that you need to decide what is the priority, the developer experience or the ease of module installation then yes, this is the question. But then again this is only interesting if you want to enable non-technical admins to install your module (and I'd be interested in having some metrics on how much people actually do this) from the admin without build support. (And this doesn't change too much on this matter.)

**Comment by Piedone** [comment]
I get the following errors when trying to build the solution:

```
Error	17	Assembly 'Orchard.Core, Version=1.9.2.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```
This is because in some projects the old System.Web.Mvc reference is still there. In most of the cases this reference wasn't actually needed, so I removed it, in other cases I fixed it with adding the package to the project.

I'd also commit/push the fix if I still have access to the fork, but one question before that: what about Web/App.config changes added by NuGet in places outside of Orchard.Web? Do we keep those? I presume they don't do anything.

**Comment by gcsuk** [comment]
@Piedone  That is strange, I haven't seen that error. I discarded the web.config changes, as they make no difference. In part this was to reduce the size of the PR, they could be committed later to save removing them every time a package is updated - I am also happy to commit them now if you prefer.

You still have access to the fork.

**Comment by Piedone** [comment]
Cool, I pushed the fix without module Web.config changes but including App.config changes for standalone projects like Orchard.Specs as I think for these the added assembly redirects are needed.

I think that we should also add all the module/theme Web.config changes too: even if they don't matter we'll constantly fight the system by  discarding those changes every time a library gets updated. What do the others think?

**Comment by Piedone** [comment]
BTW the codegen templates should be updated too, see ModuleCsProj.txt and ModuleTestsCsProj.txt.

**Comment by gcsuk** [comment]
I am more than happy to have the config file changes added, it will save time in the future.

**Comment by Piedone** [comment]
Great!

**Comment by gcsuk** [comment]
Done. NuGet has added spaces before the closing tags. Since it would always try to do this, I have left those changes too.

**Comment by gcsuk** [comment]
^^ Code generation module files ModuleCsProj.txt and ModuleTestsCsProj.txt also updated

**Pull request merged**
