### PR TITLE
Fixes #6168: Generating TechnicalName for ContenTypes, ContentFields …

### LINKED ISSUE #6168: Generating TechnicalName for ContenTypes, ContentFields creates disallowed names
When creating adding a Field to a ContentPart/ContentType with a DisplayName that already exists, a TechnicalName is generated, which contains a '-'. If we try to save, then a validation error message is display: "The technical name contains invalid characters."

So we have some disambiguity here. This might also cause problems with ContentType names.

Should "-" be allowed in TechnicalNames?

### PR DESCRIPTION
**Pull request by SzymonSel**
…creates disallowed names

Replace hyphen with underscore.
I left the separator - it's just a simpler fix

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you actually remove the separator completely? Like 'Blog2'

**Comment by SzymonSel** [comment]
Sure, will do.

-----Original Message-----

**Comment by SzymonSel** [comment]
Done

**Comment by sebastienros** [comment]
Sorry, no Regex, please do a for loop to extract the last digits. Thanks.

**Comment by SzymonSel** [comment]
Sure, will do. But why not Regex?

**Comment by bleroy** [comment]
Too heavy for such as simple check.

**Comment by SzymonSel** [comment]
Ok, thanks. Made the change as desired.

**Pull request merged**
