### PR TITLE
Fixes #5735 : ContentType name encoding in Lists

### LINKED ISSUE #5735: ContentType name encoding in Lists
ContentType's name is encoded twice on "New *ContentType*" link in *Parts.Container.Manage* view.

### PR DESCRIPTION
**Pull request by TFleury**

### CODE REVIEW

**Comment by sebastienros** [comment]
Do you think we could have an `ActionLink` taking an `IHtmlString` and would not encode it when rendered?

**Comment by sebastienros** [comment]
Either this or not use `ActionLink` when the text is localized, but render a link and use `Url.Action`

**Comment by TFleury** [comment]
I implemented `ActionLink` with `IHtmlString` linkText.
Also done the same with `RouteLink`

**Comment by sebastienros** [comment]
Much better, right ?

**Pull request merged**
