### PR TITLE
Fixed behavior of Element Controller in an around editing and updating.

### PR DESCRIPTION
**Pull request by harmony7**
This changeset is mainly changes to `ElementController`, along with some miscellaneous cleanup.

The important changes are in the `Update` method, which was (incorrectly, as far as I can tell) attempting to update the data of the element instead of allowing the `ElementDriver` to run. I wrote a bit about this in #5995.

The other miscellaneous changes are the removal of file `designer.canvas.js` (as it was completely unused) and the `Create` methods of `ElementController`, as well as a few items in the settings of the `LayoutDesignerHost` script.

### CODE REVIEW

**Comment by sebastienros** [comment]
Looks good, waiting for the iDeliverables to give it a go.

**Comment by harmony7** [comment]
The impact of this mainly for me was now I may use a View Model class that does not have field names that are necessarily the same as those on the Element (which you should be able to do).

**Comment by sfmskywalker** [comment]
I like the changes, but since I did certain things in a certain way for certain reasons, this change potentially breaks certain scenarios. However, those scenarios don't exist out of box, and I agree that it should be up to the `ElementDriver` to read from the ValueProvider, instead of updating the element's `Data` property directly (which may very well be an artifact from early iterations of the module), so I suggest we take this PR and see what gives.

**Comment by harmony7** [comment]
Thanks for accepting the PR.

@sfmskywalker yeah i figured they were probably done that way for a reason and this PR is not meant to undermine your efforts. If you can remember what those "certain situations" were, maybe we can look at those.

**Pull request merged**
