### PR TITLE
#6091: ImageProfileManager.GetImageProfileUrl can take multiple customFilters

### PR DESCRIPTION
**Pull request by musukvl**
new method was added to `IImageProfileManager`. 
`string GetImageProfileUrl(string path, string profileName, ContentItem contentItem, params FilterRecord[] customFilters);`

### CODE REVIEW

**Comment by sebastienros** [comment]
Look good. Please target the __dev__ branch instead.

**Comment by sebastienros** [comment]
Ping

**Comment by musukvl** [comment]
Hi, Sebastien,

I already requested 6091 branched from dev. And as I see, you already merged it.
https://github.com/OrchardCMS/Orchard/commit/9732c61b0fdd5b6664368d0da9f1b72afb18a095

So why do you ping?

**Comment by sebastienros** [comment]
You didn't close this one, so I thought it was still active.

**Pull request closed without merging**
