### PR TITLE
#6533 There was an error installing the requested package

### PR DESCRIPTION
**Pull request by geertdoornbos**
Package installer error handling when package not found.

### CODE REVIEW

**Comment by sebastienros** [comment]
What are you trying to fix? It's still throwing an exception, just a different one.

**Comment by sebastienros** [comment]
Also formatting is wrong (brace on the same line) and you should not use `String.Format` with `T`.

**Comment by geertdoornbos** [comment]
Currently is wrong on this [line](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Packaging/Services/PackageInstaller.cs#L57): If the package (specified by the given packageid) is not found:
- The T string will never be translated, because the packageid is in the string to be translated. There is no translation for every package signature.
- An ArgumentException is thrown while there is no wrong argument passed. An ArgumentException is thrown when one of the arguments provided to a method is not valid. That's not the case here.
The exception is not handled, resulting in the intended message (the formatted string). Exception is catched [here](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Packaging/Services/PackageManager.cs#L49) resulting in a message that is not of much use 'there was an error installing the requested package' + some permission tips.

With the fix, the string is translated as intended, the exception is catched [here](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Packaging/Services/PackageManager.cs#L46) resulting in a meaningful (as intended) message on the admin panel.

Can you elaborate (on gitter) on the issue with T inside String.Format? The T string calls the .Text property (resulting in the correct string that is used for translation) before it is used in String.Format.

**Comment by sebastienros** [comment]
Do you know how I can simulate the issue, meaning how can I try to download a package which is not found?

**Comment by BenedekFarkas** [comment]
@sebastienros repro: Modify a package install URL under "/Packaging/Gallery/Modules" so that the package ID is invalid. Without change, the exception message will not be displayed as it's caught by `PackageManager.DoInstall()` and wrapped in an `OrchardException`. As suggested by the PR, throwing an `OrchardException` (instead of `ArgumentException`) will surface the original message, so the user will get a better understanding of what's happened.

**Pull request closed without merging**
