### PR TITLE
issue 4097/5330 fix - Recipe import should update (not create) a draft content item when a matching identity is found and there is no published version of that content item

### PR DESCRIPTION
**Pull request by jimasp**
https://github.com/OrchardCMS/Orchard/issues/4097 (open)
https://github.com/OrchardCMS/Orchard/issues/5330 (dupe with full details)
https://github.com/OrchardCMS/Orchard/issues/4564 (dupe)
https://github.com/OrchardCMS/Orchard/issues/4882 (dupe)

### CODE REVIEW

**Comment by sebastienros** [comment]
Have you tried these scenarios:
- Importing a Draft when the latest is Draft (updating)
- Importing a Draft when the latest is Published (new draft)
- Importing a Published version when a Draft exists (new published)
- Importing a Published version when the latest is Published (updating)

Are there any unit tests that could be updated with these scenarios to ensure we do not regress on this later ?

**Comment by sfmskywalker** [comment]
Question: should the ```PublishedUtc``` be updated to the current time and date when importing published content items, or should those values remain untouched? Example scenario: migrating blog posts from one site to another using import/export. If the site's using the ```PublishedUtc``` to show when a post was originally published, it currently shows today's date and time for all posts since the Import method published each published item. Would it make sense to prevent that from happening, or is it recommend to use the ```CreatedUtc``` instead to display the "publication date" of the post on the front end?

**Comment by sebastienros** [comment]
@sfmskywalker I'd rather not change the current behavior

**Comment by sfmskywalker** [comment]
OK

**Comment by sebastienros** [comment]
Please add some tests

**Comment by jimasp** [comment]
sorry, very busy atm, i will get around to it when i can. please feel free to close the PR if you like, and i will re-raise when i have time to add tests etc.

**Comment by sebastienros** [comment]
We don't need to close this PR, just add more commits to your branch, and it will be updated.

**Comment by sfmskywalker** [comment]
@jimasp Can you please retarget this PR to `dev` rather than `1.9.x`? Thanks

**Comment by sfmskywalker** [comment]
Closing this one in favor of [another PR](https://github.com/OrchardCMS/Orchard/commit/98666530b4f99b6147f53d071d557761d95c02c0) including unit tests and updated Import behavior.

**Pull request closed without merging**
