### PR TITLE
Prevent no-op tasks for taxonomy field updates.

### PR DESCRIPTION
**Pull request by mvarblow**
Improves, but does not fully resolve, the performance problems described in issue #5663.

### CODE REVIEW

**Comment by sebastienros** [comment]
The change implies that if all terms have been removed, the count won't be processed. Which is wrong. Is it what you mean by "not fully resolve" ?

**Comment by mvarblow** [comment]
Actually, I think that's wrong.  If you look at TermCountProcessor.Process it does nothing if the termPartRecordIds is empty.  So we should lose nothing by not scheduling the task.  

This does not fully resolve the issue because it only makes a moderate dent in the number of tasks that get scheduled when importing content items with taxonomy fields.  The performance problem is the result of (1) the overhead of running a single task and (2) the number of tasks that are generated.  I was seeing two tasks for each taxonomy field for each imported content item.  And on quite good hardware it takes about 2 seconds of spin-up/down time (plus the time to execute the task) for each task.

**Comment by mvarblow** [comment]
The performance problem is also compounded by the fact that multiple content items may use the same taxonomy terms.  But for each taxonomy field that is updated you get a task scheduled to run on the relevant terms.  You may end up processing the same term many times.

Ideally there would be a single task to run at the end of the request.  Instead of passing the terms as a parameter to the task, the list of terms would have to be queued up somewhere.  The task would eliminate duplicates and process the queue.  An approach like this would cut the content import time by about 80% for my simple example.

**Comment by sebastienros** [comment]
@mvarblow yes, a single task. Actually that's what I am doing for blog posts if I remember correctly. 

```
        public void ProcessBlogPostsCount(int blogPartId) {
            if (!_processedBlogParts.Contains(blogPartId)) {
                _processedBlogParts.Add(blogPartId);
                _processingEngine.AddTask(_shellSettings, _shellDescriptorManager.GetShellDescriptor(), "IBlogPostsCountProcessor.Process", new Dictionary<string, object> { { "blogPartId", blogPartId } });
            }
        }
```

So this method is called every time there is a change, but itself will call the processing task accordingly. This is how we should do it, adding a level of indirection.

**Comment by mvarblow** [comment]
I just pushed some changes along those lines.  The TaxonomyService now queues up the updated terms in a HashSet and fires just a single task.  The TermsPartHandler does the same.  In addition, TermCountProcessor now checks to make sure it's not processing the same parent elements multiple times.

(I'd like to consolidate the code in TaxonomyService and TermsPartHandler into a single RecalculateCount method in TaxonomyService.  That would get us down to just a single task.  But then I'd have to change the ITaxonomyService interface.  I'd like to fix this in 1.9.x.  So a change to ITaxonomyService seems out of the question.)

**Comment by mvarblow** [comment]
@sebastienros I just pushed some changes along those lines. The TaxonomyService now queues up the updated terms in a HashSet and fires just a single task. The TermsPartHandler does the same. In addition, TermCountProcessor now checks to make sure it's not processing the same parent elements multiple times.

(I'd like to consolidate the code in TaxonomyService and TermsPartHandler into a single RecalculateCount method in TaxonomyService. That would get us down to just a single task. But then I'd have to change the ITaxonomyService interface. I'd like to fix this in 1.9.x. So a change to ITaxonomyService seems out of the question.)

**Pull request merged**
