### PR TITLE
Upgrade to .NET 4.6.1

### PR DESCRIPTION
**Pull request by aaronamm**
- Upgrade to .NET 4.6.1 which can be use with .NET Standard library 2.0
- PowerShell script tool to upgrade the .NET framework to all projects and

image

### CODE REVIEW

**Comment by aaronamm** [comment]
@sebastienros  @BenedekFarkas  I just found for using C# 6 feature, you don't need to upgrade to a newer version of .NET. However, I will let you decide if you want to keep this PR or not because PowerShell script to change targeting .NET still useful.

Thanks.

**Comment by BenedekFarkas** [comment]
Related issue: #8007, which mentions that 4.6.2 would also be nice for HTTP/2 support.

@sebastienros judging from the .NET documentation 4.6 would sufficient for that - on the other hand is there a reason not to upgrade to 4.6.2 or even higher? Hosting could be an issue if they are behind with the Windows or Windows Server version, right?

**Comment by zakaluka** [comment]
According to this (https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements), as long as the server has Windows Server 2008 R2, they can go up to .NET Framework 4.7.2 (maybe 4.7.3 also?).

**Comment by aaronamm** [comment]
@BenedekFarkas  @sebastienros  Sorry for late reply since I was on a vacation.
 I am happy to help to update to any versino.
Please let me the your decision. 
For me,  it would be nice, if we can start using a class library that supports only .NET standard library 2.0 up. 

Making a .NET standard library is a great idea to maintain only one code base and works to all platform.
It is very useful for opensource source projects.

**Comment by BenedekFarkas** [comment]
Hey, sorry for replying just now!

@aaronamm the PS script is really nice - I was doing these kinds of bulk updates with search and replace in Notepad++. :)
Maybe we can improve it a bit by processing the XML, but it might not be necessary. The concept, however is nice as we can do the same for LangVersion as well for example.

@zakaluka thanks for looking into the framework compatibility - I think we should be OK with 4.7.2 (so we support from Windows Server 2008 R2 onwards), but I'd like @sebastienros' opinion on it.

**Comment by aaronamm** [comment]
@BenedekFarkas  I think I can do it.
I will convert the PowerShell script to process XML in a PowerShell way and update the project to .NET 4.7.2.

**Comment by jean** [comment]
@aaronamm did you ever get round to that 4.7.2 update?

**Comment by sebastienros** [comment]
4.6.1 approved

**Pull request closed without merging**
