### PR TITLE
fixed one of URL prefix and Host should be required

### LINKED ISSUE #6495: multi tenant --one of URL prefix and Host should be required
obviously host field should be required to avoid my mistake at  #6434

### PR DESCRIPTION
**Pull request by infofromca**
fixed #6495

### CODE REVIEW

**Comment by geertdoornbos** [comment]
Question: If you're enforcing a requirement regarding tenant settings, what would be the safest way (location) to enforce that requirement through the whole system?
What if I would create a tenant using a console or a recipe?

**Comment by infofromca** [comment]
i have not tried console or a recipe , especially the  recipe which i think we should discuss further. but is this another issue?

**Comment by geertdoornbos** [comment]
Other scenario, same issue. Now you know this, how would you solve this issue?

**Comment by infofromca** [comment]
this fix is only for UI situation

**Comment by infofromca** [comment]
and i also got confused about recipe issue:
the purpose to use recipe is export then import.
if you export xml in which there is already URL prefix or Host(because you get it from UI),  is there any problem for importing the xml file?

**Comment by geertdoornbos** [comment]
> the purpose to use recipe is export then import

No, recipes can do much more.

I mentioned recipes as an example for a possible scenario.
You (correctly) added another case in which the requirement should be satisfied. If you're importing from XML then too the same rule should be applied.

There should be one location to enforce the requirements. No duplicate code, right?

**Comment by infofromca** [comment]
but i have not found any problem when i used recipe

**Comment by geertdoornbos** [comment]
Again, I mentioned recipes as a possible scenario that could alter tenant configuration.

**Comment by infofromca** [comment]
make the UI stronger first.
then if you have other scenarios , repo it, and open it and resovle it

**Pull request merged**
