### PR TITLE
Fix  the problem preventing reading SiteSettings from the Routes class

### PR DESCRIPTION
**Pull request by ThaerAlAjlouni**
This is a proposed fix to the issue #7362

### CODE REVIEW

**Comment by sebastienros** [comment]
Have you tried to run the Specflow tests, just to be sure we are not breaking anything? Or have you deployed it to test?
Can you try with a middelware from a module, that would use services too?

**Comment by sebastienros** [comment]
Note to myself, it's on dev so we would have time to find any issue.

**Comment by ThaerAlAjlouni** [comment]
No I haven't run Specflow tests, but I have deployed it and tested it in a middleware which I created in a custom module.

**Comment by ThaerAlAjlouni** [comment]
I am sorry, that happened by mistake

**Pull request merged**
