### PR TITLE
#5271: Added Lifecycle Status field to module manifest.

### PR DESCRIPTION
**Pull request by sfmskywalker**
- Module manifest extended with LifecycleStatus field.
- Updated Features screen to show lifecycle status if LifecycleStatus != Production.
- Updated the deprecated module manifests with the new lifecycle status (CustomForms, Media, MediaPicker and Rules).

### CODE REVIEW

**Comment by sfmskywalker** [comment]
deprecated-features
module-manifest-lifecycle-status

**Comment by dcinzona** [comment]
Awesome! :+1:

**Comment by dcinzona** [comment]
Is font-awesome available in the Admin portal?  Could we use it for icons in the sidebar for our custom modules?

**Comment by sfmskywalker** [comment]
Thanks!
No not at the moment unfortunately. However I'm sure it will become part of the new admin theme. For the time being, I had to copy the font awesome fonts and CSS into the Orchard.Modules project.

**Comment by dcinzona** [comment]
Gotcha, ok... I might make an issue for the FA implementation as sidebar icons...in fact, going to do that now so as to mark it as an enhancement

**Pull request merged**
