### PR TITLE
8773: Merge 1.10.x into dev

### LINKED ISSUE #8773: Merge 1.10.x into dev (Lombiq Technologies: ORCH-282)
Again??? But we just merged #8685! Well, further merge conflicts came up since I started that issue, but at least this time migration classes are not affected.

Also see #8779, which needs to be merged first and then that code used for the merge in #8774.

### PR DESCRIPTION
**Pull request by BenedekFarkas**
Fixes #8773

### CODE REVIEW

**Comment by MatteoPiovanelli** [comment]
Looks like the compilation step for this is failing with the same error we saw in #8746 (but form a different project).
Hopefully we have some luck figuring it out here. We've been trying to fix it, but compilation on our end doesn't fail, whether we do it in VS, or using msbuild (either with the options used in the action on github here, or the different combination we use when we release).

**Comment by BenedekFarkas** [comment]
I'll look into that, but I'm working on the merge itself right now (and some other issues I found along the way). There were new features added to the Email feature on dev that need to be integrated with Mailkit overhaul, so I'm currently validating that it's still working.

Would retargeting the Mailkit version upgrade to dev be OK for you?

**Comment by MatteoPiovanelli** [comment]
"Would retargeting the Mailkit version upgrade to dev be OK for you?"
I think so. Let me tag @AndreaPiovanelli on that as a reminder for him to check, since he was looking into it recently.

**Comment by BenedekFarkas** [comment]
@HermesSbicego-Laser @LorenzoFrediani-Laser this is a PR for integrating changes from `1.10.x` into `dev` and it affects your previously merged PRs (#7338 and #7669) due to the MailKit upgrade. I did test it all locally, but if you can, please check it out whether it's still working as expected.

**Pull request merged**
