### PR TITLE
Added Blockquote element

### PR DESCRIPTION
**Pull request by sfmskywalker**
For issue #6772

This adds a **Blockquote** element to the toolbox, making it awesome for users to add beautifully styled block quote elements to their page.

image

### CODE REVIEW

**Comment by DanielStolt** [comment]
Tested and reviewed, looks and works fine, both code and functionality.

However, I think we should also add a "citation" property to the element, allowing editor control of the rendered `cite` attribute:

``` html
<blockquote cite="http://developer.mozilla.org">
  <p>This is a quotation taken from the Mozilla Developer Center.</p>
</blockquote>
```

**Comment by sfmskywalker** [comment]
Thanks for reviewing! I added the `Citation` property.

**Comment by sebastienros** [comment]
Why not an HTML section instead of content ?

**Comment by sfmskywalker** [comment]
Section, as in a new Category called HTML containing HTML elements? I would not be opposed to that.

**Pull request merged**
