### PR TITLE
Fixes usage of undeclared variables in Link.Edit.cshtml.

### PR DESCRIPTION
**Pull request by jtkech**
As requested by @DanielStolt 

Best.

### CODE REVIEW

**Comment by sebastienros** [comment]
Was it the only known merge issue?

**Comment by jtkech** [comment]
Sorry, i don't know.

Just done this one because @DanielStolt had this issue and asked me to fix it.

But i've quickly checked field views, seems that only this one was using undeclared variables.

**Comment by agriffard** [comment]
See #7374 .
I think the pb is in dev, master and 1.10.x

**Comment by jtkech** [comment]
Oh yes and the workaround was to rather declare variables and init them by checking default values.

    var isRequired = settings.Required && String.IsNullOrWhiteSpace(settings.DefaultValue);
    var isTextRequired = settings.LinkTextMode == LinkTextMode.Required && String.IsNullOrWhiteSpace(settings.TextDefaultValue);

Not sure at 100% but because now default values are proposed values when 1st creating items. I think that now we don't need to check default values here.

Before, when a default value was provided, if the user didn't input a value on a required field, it was allowed because the default value was used on server side. But now, default values are used as proposed values on 1st creation, not as default value when the field is posted with an empty value. But just as i remember.

**Pull request merged**
