### PR TITLE
Use NuGet instead of lib folder

### PR DESCRIPTION
**Pull request by gcsuk**
RE: https://github.com/OrchardCMS/Orchard/issues/6148

This PR updates all assembly references from the lib folder to NuGet, where a NuGet version is available. Some custom assemblies, and javascript files, have been left in “lib”

Recommend reviews done with “w=1” on the URL to remove whitespace changes.

Where possible, the exact same version has been used from NuGet. The following packages have no version changes:

Autofac
Azure
Castle
DotNetZip
ImageResizer
IronRuby
Log4Net - Package 2.0.3 contains assembly 1.2.13 (unchanged)
Lucene
MVC
Newtonsoft.Json
NHibernate
npgsql
Owin
Redis
Specflow
XMLDiffPatch
WebApi

The following references are different, but no further than a Minor version change. This is because the lib versions are old so NuGet doesn’t have them available

HtmlAgilityPack: 1.3.9.1 >>> 1.4.9.0
Moq:  4.0.812 >>> 4.0.10827
MySql: 6.5.4.0 >>> 6.7.9.0
NUnit: 2.5.2.9222 >>> 2.5.10.11092

The following assemblies have been left in lib folder as they are not available on NuGet or have breaking changes:

FluentPath
MSBuild
MSDeploy
MSTranslitTools
NHibernate.Linq (custom build)
NuGet
SqlCe
TypeScript

### CODE REVIEW

**Comment by bleroy** [comment]
FluentPath is on NuGet: https://www.nuget.org/packages/FluentPath/

**Comment by gcsuk** [comment]
There is a build error with the NuGet version :(

**Comment by gcsuk** [comment]
I was going to ask @sfmskywalker to contact you about it actually :)

**Comment by bleroy** [comment]
I'm not surprised as I think Orchard is using a very old version. Let's ignore that for the moment. Can you file a separate bug about refreshing usage of FluentPath to the latest, or refactor to remove the dependency?

**Comment by gcsuk** [comment]
Of course @bleroy - my thought was to get this PR in, then address bringing in FluentPath. 

NHibernate.Linq may also need attention.

**Comment by gcsuk** [comment]
The final commit which removes lib folders is preventing GitHub from showing all changes. Happy to revert this (intentionally left until last) to ease review if a committee member prefers this.

@piedone I think you started this work a while ago, I spotted a stale branch with similar name

**Comment by Piedone** [comment]
Line endings in some files were fixed in the Orchard source, that's why this PR now has merge conflicts.

Please sync your fork with the Orchard repo and merge the target branch of this PR into your branch (for a guide see: https://help.github.com/articles/syncing-a-fork/ or alternatively if you use GitExtensions you can simply add https://github.com/OrchardCMS/Orchard.git under Repository/Remote repositories, do a fetch all and then merge the target branch into your branch).

If you have files appearing changed in your working directory that you didn't change but were actually touched by git to normalize line endings then you don't need to commit those (these were also fixed): clear the contents of the .gitattributes file in the repository root or remove the file, then do the merge. The changed files won't appear now (.gitattributes instructs git to care about line endings) but please don't commit the .gitattributes change (you can simply reset that change).

There shouldn't be too many merge conflicts and most of those should be resolved automatically by the merge tool (in GitExt hit Start merge tool and it will be able to do the merges).

Sorry about the inconvenience. On the upside this leftover from the hg to git conversion is now gone :-).

If you need further help just ping me here.

**Comment by gcsuk** [comment]
Hi @Piedone I've been having a nightmare with Git all afternoon trying to get my branch to not be broken because of Line Endings. I cannot discard any of what it thinks are changes, they instantly reappear. I tried deleting the gitattributes file but it made no difference.

I am stuck, could you please take a look? You have collaborator access to my repo.

**Comment by Piedone** [comment]
Done now. Sorry again.

**Comment by gcsuk** [comment]
Thanks. Do you know how I am going to pull down the latest branch? It won't let me because it thinks I have uncommitted changes, and I cannot discard them.

**Comment by Piedone** [comment]
You can fetch and then checkout instead.

**Comment by Piedone** [comment]
@gcsuk BTW noticed just now that you summoned me earlier, but I didn't get any notification about this strangely... What I did previously regarding NuGet and Orchard was orthogonal to this: it was about providing Orchard itself as NuGet packages so you could basically add Orchard from NuGet to your project and thus "orchardize" it.

**Comment by gcsuk** [comment]
Replaced by https://github.com/OrchardCMS/Orchard/pull/6217 after I ruined this branch

**Pull request closed without merging**
