### PR TITLE
#5786 Add support for persisting flags based enums

### LINKED ISSUE #5786: Add support for persisting flags based enums
This issue runs on from the following discussion here http://orchard.codeplex.com/discussions/403831#post1078496

The idea being that a new FlagsEnumConvention be created to allow flags enums to be persisted (where multiple values are set - ORed).

### PR DESCRIPTION
**Pull request by mjy78**
This enhancement enables content part fields that are enums with the Flags attribute to be persisted to the database.

Fixes #5786

### CODE REVIEW

**Comment by sebastienros** [comment]
Mind adding a small unit test to show the usage and ensure it's not broken?
Look for the ones that check for text blobs for an example.

**Comment by sebastienros** [comment]
Waiting for a unit tests and merge conflicts to be fixed.

**Comment by sebastienros** [comment]
Please also fix the merge conflicts

**Comment by mjy78** [comment]
@sebastienros I'm looking to setup a unit test for this. What class is the text blob example you referred to above contained in?

**Pull request closed without merging**
