### PR TITLE
Orchard.Resources - Consolidate third-party client-side resources into dedicated module

### LINKED ISSUE #5438: Consolidate third-party client-side resources into dedicated module
We have discussed this in a few meetings, and I'd like to get started on this.

To recap, the idea is to take all of the third-party client-side libraries we have scattered across different modules and move them all into a module dedicated to just this purpose. We could reuse the `Orchard.JQuery` module but rename it to something more general like `Orchard.Resources`. It would include the jQuery resources of course, but also other things.

The new module would not contain anything except a bunch of third-party libraries in the form of LESS, CSS and JavaScript resources. It would contain a resource manifest and define resources for these libraries, so that other modules/themes can require them. The advantages would be less duplication, standardization on one version of these libraries across the codebase, and less problems with conflicts when multiple modules/themes try to include their own versions of these libraries.

The new module would ideally define these resources both on a granular level (individual components) and as well-defined larger packages grouping the smaller components for convenience. E.g. Bootstrap contains a bunch of smaller components that one should be able to require individually, but there should also be a big-ass Bootstrap resource defined by the module that gives you everything.

Things to include in the initial release of new `Orchard.Resources` module:

- jQuery
- jQuery UI
- jQuery BlockUI (used by Azure Media Services)
- jQuery FileUpload (used by Media Library and Azure Media Services)
- Angular.js (used by Layouts)
- Bootstrap (used by Layouts, and will be used by the new upcoming admin theme)
- CodeMirror (used by Email Templates and will be used by new Markdown editor)
- Underscore.js (used by Layouts and Azure Media Services, probably others too)
- Moment.js (used by Azure Media Services) 
- Uri.js (used by Azure Media Services)

This is just a starting point, the ones I can think of OTOH - feel free to add to this list!

Personally I would also love to have one unified build pipeline using Gulp for all of these resources. In other words, we should add them in their "purest" form (LESS where available, CSS otherwise, non-minified versions) and let our build script do:

1. LESS compilation
2. Minification
3. Bundling (where appropriate)
4. Source mapping
5. Vendor prefixing

I think we should do all this work in a feature branch off `dev`.

Thoughts?

### PR DESCRIPTION
**Pull request by sfmskywalker**
This adds a new module called `Orchard.Resources` which contains third-party client-side resources and basically deprecates `Orchard.jQuery`.

Fixes #5438

### CODE REVIEW

**Comment by agriffard** [comment]
FontAwesome 4.5 has been released : https://github.com/FortAwesome/Font-Awesome/releases/tag/v4.5.0
Are there specific guidelines concerning the upgrade of a library?

It makes me think : Would it be possible to create a page in the admin that displays the list of all the styles or scripts available with their information (feature, version, cdn, ...) ?

**Comment by sfmskywalker** [comment]
Good! I don;t have any specific guideline, but this is what I typically do:

1. Replace the existing library files with the new ones.
2. Update Assets.json if necessary (in case file names have changed).
3. Run Gulp from the Task Runner.
4. Clear the browser's cache and do some smoke testing.
5. Push & Pray.

**Comment by sfmskywalker** [comment]
I'm sure such a page would be possible and it would be interesting to look at, but in what way do you think this to be useful?

**Comment by agriffard** [comment]
I guess that if you are a front end developer or a theme designer, it would be easier to know which key you can use to require a resource and which ones are available (without having to create it).

**Comment by sfmskywalker** [comment]
That's a good point. Easier to look at a screen than having to find all implementations of `IResourceManifestProvider`.

**Pull request merged**
