### PR TITLE
Fix on Content Picker Field rendering

### PR DESCRIPTION
**Pull request by GiuseppeMusso-Laser**
Fix on Content Picker Field rendering when feature Orchard.ContentPicker.LocalizationExtensions is enabled, as described in issue #7630.

### CODE REVIEW

**Comment by sebastienros** [comment]
The code you are modifying has an issue. The localized translations should not be passed directly in JavaScript form because you will have two issues:
- The localized text will be double-encoded ( `.Text` is called then `@`)
- If the localization contains a `"` then it will break the javascript

The solution to read localized values in JS from a view is to put the value in a tag like this:
`<input type="hidden" id="deleteMessage" value="@T["Are you sure you want to delete this folder?"]" />`

then read it using `document.getElementById('deleteMessage')`

can you please change it on this view?

**Comment by GiuseppeMusso-Laser** [comment]
I modified the code in order to avoid double-encoding and I put the value in a hidden field as you suggested.
Then I realized it is all fine till the translation does not contain a quotation mark (eg.: "Selected \"items\" with ...").
In this case, the quotation mark breaks the value.
To avoid this problem I got the translated string using T("...").Text.Replace("\"", "&quot;") and put it in html tag (hidden field value) using Html.Raw().
Is there a better way to deal with this problem?
I'm also aware quotation mark is the problem because hidden field value is enclosed in quotation marks.
I could have a similar problem with single quotes if my value was enclosed in single quotes.

**Comment by sebastienros** [comment]
Not right.

if you just insert the translation like this:

`<input type="hidden" value="@T["BLAH"]" />` then the quote will be encoded in HTML.

Don't call `.Text` and you won't have any issue.

**Comment by GiuseppeMusso-Laser** [comment]
Sorry, I think I'm misunderstanding something.
If I write in cshtml view:

`<input type="hidden" id="tryTranslateMsg" value="@T("One \"two\" three.")" />`

I get in the page source in my browser:

`<input type="hidden" id="tryTranslateMsg" value="One "two" three." />`


so js code:

`hint.innerText = $("#tryTranslateMsg").val();`

sets hint value to "One " because double quotes breaks hidden field value.

It looks like @T("...") does not HTML-encode double quotes.
Could you please help me to understand where I'm wrong?

**Comment by sebastienros** [comment]
I will investigate, looks like an issue in how the text is encoded.

**Comment by sebastienros** [comment]
Found the solution, you need to use `.Text` as you were doing, but in the `input` tag.

```
<input type="hidden" value="@T("\"Foo\"").Text"/>
```

**Comment by GiuseppeMusso-Laser** [comment]
Great, now it works fine for me.
Thank you, Sébastien!

**Pull request merged**
