### PR TITLE
Added password to IUserEventHandler.PasswordChanged event

### PR DESCRIPTION
**Pull request by sfmskywalker**
See #6937

### CODE REVIEW

**Comment by DanielStolt** [comment]
I see you didn't go with the new complex type approach - how come?

In any case, I thought the name suffix "Context" was inappropriate for the suggested type, because in my mind, that suffix suggests that handlers can interact with the context object to somehow alter the outcome of the event, because that seems to be the convention in Orchard for context objects. "Args" or "Info" would have been better name suffices for this reason IMO.

Anyway, you didn't end up using the object, so... don't know why I'm mentioning it. :)

**Comment by sfmskywalker** [comment]
I am pleased you asked!

In hindsight, other methods on this interface also accept an extra argument called `password`. Introducing a complex type argument for just the one method would then seem arbitrary. So I think it would be better to do it either all the way, or don't do it (and risk needing to break the interface yet again in the future, however unlikely in my mind).

Regarding the suffix "Context" vs "Args" or "Info": I considered the suffix 'Args", but I couldn't find any previous usage, plus it seems to be a convention used with actual .NET events. Then again, they are using "EventArgs" as a suffix. "Info" I hadn't thought of.

But the main question is: should we completely overhaul the interface with complex type arguments, or just a select few members (yet to be determined), or keep my PR as-is?

**Comment by DanielStolt** [comment]
I see - agree with your assessment.

Regarding the main question, I'm not aware of the additional needs beyond this PR, but if your PR as-is solves the issue, then personally I would vote for keeping it.

**Comment by sebastienros** [comment]
Broken PR, I know who did this to you but won't blame them.

**Pull request merged**
