### PR TITLE
upgrade microsoft.net.compilers to 2.4.0

### PR DESCRIPTION
**Pull request by aaronamm**
Upgrade all projects that have Microsoft.Net.Compilers to version 2.4.0

### CODE REVIEW

**Comment by sebastienros** [comment]
@BenedekFarkas related to your changes?

**Comment by aaronamm** [comment]
@sebastienros  Thanks for helping update.

**Comment by BenedekFarkas** [comment]
@sebastienros yes! Unfortunately, I think it would be easier if we rejected the PR (sorry @aaronamm), because this is just one part of the upgrade process of the Dynamic Compilation changes we already made on 1.10.x. Btw 1.10.x includes Microsoft.Net.Compilers 2.9.0 (the current latest version), 2.4.0 is a year old.
So we'll upgrade dev to 2.9.0 as well soon.

**Comment by aaronamm** [comment]
@BenedekFarkas Do you want me help update `dev` branch to 2.9.0? I am happy to help. 
Not sure about your plan, will you merge `1.10.x` back to `dev` to get the upgrade. My PR just want to make everything consistency. ^^

**Comment by BenedekFarkas** [comment]
@aaronamm yep, 1.10.x (or actually, probably the commit on 1.10.x that will be marked as the 1.10.3 release) will be merged to dev (and btw the minor version branch is more or less regularly merged into the major version branch), so most of this work is already done (on 1.10.x), there's only a couple more modules on dev that aren't on 1.10.x.

On the other hand, `Microsoft.Net.Compilers` is needed anymore separately (it's completely removed on 1.10.x now), because `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` ships with it included (since version 2.0.0 I think).
1.10.x has the 2.0.1 version, so that includes the 2.10 compiler package (but a newer one has been released recently, so probably DotNetCompilerPlatform will have a new release soon as well).

So thanks and sorry, I'll close this PR, but we can coordinate on other updates (such as the other thread I just commented to).

**Comment by aaronamm** [comment]
Thank you ^^

**Pull request closed without merging**
