### PR TITLE
[8100] Removing wrong aliases

### PR DESCRIPTION
**Pull request by d-lan1**
See issue  https://github.com/OrchardCMS/Orchard/issues/8100

### CODE REVIEW

**Comment by sebastienros** [comment]
@HermesSbicego-Laser are you ok with that?

**Comment by HermesSbicego-Laser** [comment]
I agree that there is an issue here, but I do not agree with the proposed fix.
Instead of changing the `RemoveAlias` method adding a boolean, I would suggest to pass the AutoroutePart of the `published content`  (and not the autoroute of the `current` one, the `latest` using the admin UI ) to RemoveAliases method `_autorouteService.Value.RemoveAliases(part);`.
If we opt for this solution, the call to the handlers should be moved to their "ing" methods (removing, unpublishing, detroying).
More, with the code proposed by @1996dylanriley this case will not be managed:
1. Create a page (alias=page) and publish it
2. Modify the alias (alias=page2) and Save it
3. Delete/remove/unpublish the content. 
The alias will still be there in the table.

**Comment by d-lan1** [comment]
@sebastienros will you be implementing the changes suggested by @HermesSbicego-Laser ? Thanks guys.

**Comment by sebastienros** [comment]
I won't, I'll wait for a contributor to do it.

**Comment by HermesSbicego-Laser** [comment]
@1996dylanriley, we have not so much time in this period so we can't implement it right now. By the way, it should be a simple fix so if you write the code we can test and validate it in our environments... If you need some code snippets to work on, feel free to ask.

**Comment by BenedekFarkas** [comment]
We closed the #8100 issue for 1.10.3 (because #8150 was merged), but to be sure I tried to repro the problem and it seems it's working OK, so I'm closing this.

**Pull request closed without merging**
