### PR TITLE
Ensure that CDN protocol relative URLs support ssl

### PR DESCRIPTION
**Pull request by thekaveman**
For #6941

### CODE REVIEW

**Comment by sebastienros** [comment]
Oh, I was actually thinking about changing the hard coded urls instead of doing it automatically ;)

**Comment by sebastienros** [comment]
Not saying it's not better.

**Comment by thekaveman** [comment]
That's what I meant by the "quicker option" :wink:

I'm also thinking of `Script.Include("//cdn.com/asset.js")` type situations; this fix would not cover, correct? Should we be concerned about that scenario?

**Comment by sebastienros** [comment]
The more I think about it the more I think we should just update the urls in the resource files. Because maybe a user really need to use `//`. We should just change the urls we manage.

**Comment by thekaveman** [comment]
Fair enough. I'll close this one and submit a new one with those changes.

While I'm at it though, there is one minor addition we should consider: if the user entered `//`, this should imply `CdnSupportsSsl`, correct? 

In other words, this code that looks for `https` at the beginning:

```csharp
else {
    CdnSupportsSsl = cdnUrl.StartsWith("https", StringComparison.OrdinalIgnoreCase);
}
```

should be expanded to look for `//` **or** `https` at the beginning, right?

Even though we may not output `https`, it is true that if the CDN supports protocol relative, it supports SSL.

**Comment by anoordende** [comment]
Just as a bit of background, the only reason for the assumption `CdnSupportsSsl = cdnUrl.StartsWith("https", StringComparison.OrdinalIgnoreCase);` is backward compatibility, so that (hopefully) the majority of existing setups keep serving under https even with the CdnSupportsSsl flag omitted.

Just a radical thought, what we are heading towards is the convention that if the CDN URL starts with `https` (or `//` if  you like) it supports SSL, otherwise it does not. My gut reaction is that we can deprecate CdnSupportsSsl altogether.

And keep in mind that we are only indicating SSL support, we're not indicating if SSL should actually be used. Control can be given back by an Admin option along the lines of:

- Always use SSL for CDN resources [that support it] even when the site is insecure
- Only use SSL for CDN resources [that support it] when the site is secure
- Never use SSL for CDN resources (this would be a testing thing only I expect)

**Comment by BenedekFarkas** [comment]
@thekaveman and @anoordende thanks for your input!
We've decided deprecate the CdnSupportsSsl parameter in 1.10.x (for 1.10.4) and remove it in dev (for 1.11).

**Pull request closed without merging**
