### PR TITLE
Orchard.Fields, added proper support for "not required" setting of DateTimeField

### PR DESCRIPTION
**Pull request by ViRuSTriNiTy**
see issue https://github.com/OrchardCMS/Orchard/issues/6966

### CODE REVIEW

**Comment by infofromca** [comment]
@ViRuSTriNiTy this fix should go to 1.10.x pls

**Comment by ViRuSTriNiTy** [comment]
@infofromca Is it my task to change to 1.10.x? When this is the case how do i do this?

**Comment by ViRuSTriNiTy** [comment]
Created a new pull request, see #7248

**Comment by rtpHarry** [comment]
For future reference, sometimes you can do this via the GitHub UI now.

Click Edit and the base is selectable:

image

Sometimes it makes a mess though as too much is different between the branches.

The feature was only added in last few months so it probably wasn't available when you asked in June.

**Pull request closed without merging**
