### PR TITLE
Remove lock from dictionary when disposing

### PR DESCRIPTION
**Pull request by imranazad**
Fixes https://github.com/OrchardCMS/Orchard/issues/8391

### CODE REVIEW

**Review by jtkech — APPROVED** [review]

**Comment by jtkech** [comment]
Fixes #8391 

@imranazad for infos when specifying `Fixes #8391`, as i did above, the related issue will be automatically closed when the PR will be merged

**Comment by imranazad** [comment]
@jtkech Thank you for the info, good to know. :-) Thanks again for all your help. Take care and be safe.

**Comment by imranazad** [comment]
@jtkech Btw what is the process for getting this merged into 1.10.2?

**Comment by jtkech** [comment]
Hmm, i think you need to create a new PR and target the `dev` or maybe beter to target the `1.10.x` branch so that it will be part of the next release, @BenedekFarkas ?

**Comment by imranazad** [comment]
@jtkech  Thanks I've targeted 1.10.x and created a new pull request: 

https://github.com/OrchardCMS/Orchard/pull/8395

I'll close this pull request as it's no longer needed.

Thanks

**Pull request closed without merging**
