### PR TITLE
#6736: Changed UrlPlaceholder to TextPlaceholder

### PR DESCRIPTION
**Pull request by MechMK1**
Fixes OrchardCMS/Orchard#6736

### CODE REVIEW

**Comment by agriffard** [comment]
Wrong one. Line 30 was correct because it is related to the Url.

This is the one line 41 that has to be changed.

**Comment by MechMK1** [comment]
My fault. I reverted my commit and changed the correct line now.

**Comment by sebastienros** [comment]
Should it target 1.10.x instead ?

**Comment by MechMK1** [comment]
I assumed dev was the correct branch. If you want me to merge into 1.10.x instead, I'd have to make another PR (possibly)

**Comment by sebastienros** [comment]
Any non-breaking change should go in 1.10.x to be released more quickly. If you don't mind then please target 1.10.x, thanks.

**Comment by MechMK1** [comment]
Should I close this PR and make a new one? Or is there a way to change my PR target branch?

**Comment by sebastienros** [comment]
You need to close the PR, I imagine a world where we could change the target branch by ourselves ...

**Comment by MechMK1** [comment]
Then I'm going to close this one and move everything to PR #6758

**Pull request closed without merging**
