### PR TITLE
ContextState Compromise

### PR DESCRIPTION
**Pull request by jtkech**
Ending this discussion https://github.com/OrchardCMS/Orchard/commit/42e71fe9fa2cc5337eb9239d68a08a2b680f3df2#commitcomment-16323433 with @DanielStolt and @sfmskywalker, here a last compromise to try that is, as said by sipke, basically the same as it is now...

- Still use the `HttpContext` during a web request because this is more reliable.
- Use the new `IsBackgroundHttpContext()` extension to check if it's a valid context.
- Nevertheless, replace `CallContext.Get/SetData()` with `CallContext.LogicalGet/SetData()`.
- (The last point is easy to revert if some drawbacks)

Best

### CODE REVIEW

**Comment by sebastienros** [comment]
Unit tests are failing after this PR

**Comment by sebastienros** [comment]
See teamcity.codebetter.com

**Comment by sfmskywalker** [comment]
Checking...

**Comment by jtkech** [comment]
Me too, i'll try unit tests to understand why.

**Comment by sfmskywalker** [comment]
Strange, the failing unit test on TC passes on my local. On TC, the unit test reports a 500 Internal Server Error. Maybe it's temporary?

**Comment by sfmskywalker** [comment]
image

**Comment by sebastienros** [comment]
It it passes locally, we'll wait for the next time it runs to be sure it repros.

**Comment by jtkech** [comment]
`StatusCodeShouldBe404ForUnexistingResources()` also passes on my local environement.

**Comment by sebastienros** [comment]
This time more than 20 tests don't pass

**Comment by sfmskywalker** [comment]
Weird. AppDomainUnloaded exceptions. I'll revert the change set tonight and see if that helps.

**Comment by jtkech** [comment]
@sebastienros, @sfmskywalker just seen your comments.

Because `ObjectHandle` inherit from `MarshalByRefObject`, and you are talking about AppDomain exceptions, not sure at all but i suspect a cross domain lifetime problem. So, maybe worth to add this at the beginning of the `ContextState` class:

    //using System.Runtime.Remoting; // no more used
    ...
    public class ContextState<T> where T : class {

        internal class ObjectHandle : System.Runtime.Remoting.ObjectHandle {
            public ObjectHandle(object o) : base (o) { }
            public override object InitializeLifetimeService() {
                return null;
            }
        }
    ...

Best

**Comment by jtkech** [comment]
Just to try, PR #6498 done.

Sorry again for the downside.

**Comment by jtkech** [comment]
@sebastienros, @sfmskywalker 

My last update solves some exceptions but creates new ones (seen on teamcity that currently runs).

But just seen that i can also run Specs in my local environement (not only unit tests). And i can repro the exact same errors.

So, if possible let me one day more to try to solve this. Note: maybe 2 days because right now i need to leave and i can re-work on this the next night.

Best.

**Pull request merged**
