### PR TITLE
Ibn labs/additional module directories dev 5

### LINKED ISSUE #5019: Ability to load extensions from different folder
@Piedone created:
https://orchard.codeplex.com/workitem/21190

It would be great to be able to load modules and themes from other folders than just the default Modules and Themes folder.

There is partial support for this today (IExtensionFolders) but the strings "~/Modules" and "~/Themes" are hard-coded in many places that prevent you from e.g. using templates from modules stored in a different folder than /Modules.

Being able to use arbitrary extension folders (defined in e.g. Web.config, HostComponents.config) would be a step forward. Still, since it's a web app operating with virtual paths you'd have to place your extensions under Orchard.Web (though you could do that into new folders).

Particularly Drupal lets you place your own extensions under a different folder than the built-in ones: https://www.drupal.org/node/2116781

Also see: https://orchard.codeplex.com/discussions/570620

### PR DESCRIPTION
**Pull request by qt1**
Commit from squashed 1.9.x applied to dev and conflict resolution performed.

intended to resolve #5019, #5241, #5354

### CODE REVIEW

**Comment by sebastienros** [comment]
Yeah ;) Should be pull during today's triage.

**Comment by sebastienros** [comment]
Well, your commit list should not contain the commits from dev ... Did you do the merge in the correct order? This PR looks good with 1 commit: https://github.com/OrchardCMS/Orchard/pull/5982

**Comment by qt1** [comment]
Base of this commit is latest dev.  Flat version of 1.9.x (#5982) merged to base(dev). Extra files changes between dev and 1.9.x discarded individually. One conflict in web.config resolved.

**Comment by sebastienros** [comment]
We'll see how it goes in the CI

**Comment by qt1** [comment]
Thanks!

**Pull request merged**
