### PR TITLE
Fixes #6113 : Anchor custom link on homepage produces bad href

### LINKED ISSUE #6113: Anchor custom link on homepage produces bad href
Requires using empty UrlPrefix to reproduce.

## Steps to repro
Create an anchor custom link on the home page (e.g.: Url = `~/#contact`)

On the homepage, menu widget renders the correct Href : `/#contact`

On any other page, it renders a bad Href. (e.g.: on `/my-page` it renders `/my-page#contact` instead of `/#contact`)

Issue seems to be located in `NavigationManager`'s `GetUrl`method.

### PR DESCRIPTION
**Pull request by TFleury**

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you provide a repro of the issue? We are lost in the `if`s

**Comment by TFleury** [comment]
Repro steps in the issue : #6113

**Comment by Piedone** [comment]
Line endings in some files were fixed in the Orchard source, that's why this PR now has merge conflicts.

Please sync your fork with the Orchard repo and merge the target branch of this PR into your branch (for a guide see: https://help.github.com/articles/syncing-a-fork/ or alternatively if you use GitExtensions you can simply add https://github.com/OrchardCMS/Orchard.git under Repository/Remote repositories, do a fetch all and then merge the target branch into your branch).

If you have files appearing changed in your working directory that you didn't change but were actually touched by git to normalize line endings then you don't need to commit those (these were also fixed): clear the contents of the .gitattributes file in the repository root or remove the file, then do the merge. The changed files won't appear now (.gitattributes instructs git to care about line endings) but please don't commit the .gitattributes change (you can simply reset that change).

There shouldn't be too many merge conflicts and most of those should be resolved automatically by the merge tool (in GitExt hit Start merge tool and it will be able to do the merges).

Sorry about the inconvenience. On the upside this leftover from the hg to git conversion is now gone :-).

If you need further help just ping me here.

**Comment by TFleury** [comment]
PR sync'd

**Pull request merged**
