### PR TITLE
Glimpse

### PR DESCRIPTION
**Pull request by paynecrl97**
Issue number #5419, previous PR #6243.

This PR adds the first set of Glimpse functionality to Orchard.

On top of Glimpse's default MVC and .Net instrumentation, the following Orchard tabs are also available:

- Authorizer
- Cache Service
- Content Manager
- Content Parts
- Layers
- Shapes
- SQL (See issue below)
- Widgets

Each tab exists in its own feature, meaning the instrumentation can be toggled on or off as required.

The following extension points exist:

- Ability for other modules to add data to Glimpse
- Ability for other modules to consume the messages sent to Glimpse (example use cases- build a live stats dashboard, push the data into a db to be aggregated, push data to a 3rd party service eg New Relic etc...)

*There are many more areas of Orchard that could be instrumented, but this is just a start.*

There is an issue with the SQL tab where the number of open connections is being over-reported. Someone with more NHibernate ability than me will have to investigate the cause.

There are a number of concessions, but I feel that the value of Glimpse is too great to not make these concessions:

- All Glimpse config is contained within the web.config as opposed to being configurable in the back office
- Glimpse's DI framework will not currently allow for Orchard services to be injected into it
- Any module that adds a tab to the Glimpse console needs to be referenced by the `Orchard.Web` project

All of these issues could probably be corrected over time.

This is also the first usage of `IDecorator` (other than tests) in the Orchard source.

### CODE REVIEW

**Comment by sebastienros** [comment]
Demo on Tuesday?

It doesn't affect anything outside Orchard.Glimpse which is good. Should we also make ShapeTracing obsolete BTW ?

**Comment by paynecrl97** [comment]
Will demo on Tuesday.

As it stands, the current shapetracing feature is more complete than what Glimpse offers. No reason not to port it over to Glimpse at some point however.

**Comment by Jetski5822** [comment]
Hey Chris,

Have you looked much at Glimpse on Dotnet Core?

N

**Comment by paynecrl97** [comment]
@Jetski5822 

I have not (yet).

I spoke with Anthony from the Glimpse project a while back and he walked me through what they were wanting to do with Glimpse v2 which I believe is Dotnet Core (and I see you have 2 commits in this project), but that's about it.

I am planning on porting this over to Orchard v2 at some point once this PR is merged and I get some free time.

**Comment by paynecrl97** [comment]
@sebastienros Release transform to disable Glimpse added, and merge conflicts resolved

**Pull request merged**
