### PR TITLE
Format site.css.

### PR DESCRIPTION
**Pull request by goh-chunlin**
Removed unnecessary comments (commented out code is not recommended) and empty rulesets.

### CODE REVIEW

**Comment by sebastienros** [comment]
Please fix the merge issues

**Comment by goh-chunlin** [comment]
Which merge issues are you referring to? @sebastienros

**Comment by sebastienros** [comment]
We reverted the commit which made this PR unmergeable. Should be merged tomorrow during the triage meeting, thanks.

**Comment by sebastienros** [comment]
Sorry, I will close this PR as @sfmskywalker will merge a huge PR with the new Admin theme that will annihilate this change. Thanks for the effort.

**Pull request closed without merging**
