### PR TITLE
Fixing #4963

### PR DESCRIPTION
**Pull request by Skrypt**
To prevent translations that are using ' char like : Certains éléments n'ont pas été enregistrés.
To fail.

Fixing #4963

### CODE REVIEW

**Comment by sebastienros** [comment]
the solution is to use `HttpUtility.JavascriptEncode`

**Comment by sebastienros** [comment]
At the same time please check for other occurrences of `'@` and `"@`.

**Comment by Skrypt** [comment]
Done, in contrary of what I was thinking there was only 2 occurences of this in the code. Plus, I fixed the javascript to display those correctly when using encoded chars. For some reason, when using a message in a confirm you need to put it in a HTML element for him to decode it in HTML else it will display the encoded string.

**Comment by sebastienros** [comment]
Please target 1.9.x

**Pull request closed without merging**
