### PR TITLE
#2839 reverse order of page title and site name, SEO improvement

### PR DESCRIPTION
**Pull request by yaplex**
solution for people who don't like to override too much pages from base templates. ticket #2839 

Alex
https://yaplex.com

### CODE REVIEW

**Comment by yaplex** [comment]
It's fixed the way you suggested in ticket, I fixed "GenerateTitle" method in PageTitleBuilder.

**Comment by sebastienros** [comment]
We can't change this that easily, it would break what people have done so far.
I think I have created an issue explaining what should be done instead. The general idea was that title parts could be added with an optional `Position`, with the same logic as wherever we use positions already (1, 1.2, ...). This way it is not breaking, and you can force a specific one to come first. 

Would you mind trying it?

**Comment by yaplex** [comment]
Where exactly are you using position? I found class Position.cs but don't think it's what you telling, I looked into ShapePosition class, but looks like it's also not what you mean.

**Comment by sebastienros** [comment]
What I mean is that you add an override which takes another string as parameter, called `position`. And the default value is `"5"`. When we render the items, we first order them with  `Orchard.UI.FlatPositionComparer`.

**Comment by yaplex** [comment]
Sorry, but it's not clear for me. 
There is a helper method 
public static MvcHtmlString Title(this HtmlHelper html, params string[] titleParts)
which is called this way  @Html.Title(title, siteName)
I don't think this method can accept another parameter, because of "params" keyword

I looked into details of implementation of FlatPositionComparer, and if I make Title method accept my new type instead of string, I can have Position property there. Soemthing like this:
public static MvcHtmlString Title(this HtmlHelper html, params TitlePart[] titleParts)
where TitlePar is 
class TitlePart{
string Title{get;set}
string Position{get;set}
}

and the using will be 
@Html.Title(new TitlePart{Title="Hello",Position="1"}, 
new TitlePart{Title="Word", Position="2"})

If you talking about something else, could you please specify more details, I am sorry but I start learning Orchard development just a couple of month ago, so some obvious tasks make require additional explanation.

**Pull request closed without merging**
