### PR TITLE
fix for #6330

### PR DESCRIPTION
**Pull request by ryanmagoon**
Changed extension manifests to use “orchardproject.net” as the Website

### CODE REVIEW

**Comment by Jetski5822** [comment]
Hey cool - but is there any reason why you are missing the scheme off of the url?

**Comment by ryanmagoon** [comment]
I followed the issue a little too exactly, huh 🤔
-- 
Ryan Magoon

**Comment by Jetski5822** [comment]
haha - i think so!!! Change it to 

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.CodeGeneration/CodeGenerationTemplates/ThemeManifest.txt#L3

across the board! - but still, good stuff!

**Comment by ryanmagoon** [comment]
Done

**Comment by sebastienros** [comment]
Can you squash your commits? It's simple, checkout the branch of the PR you are working on, reset the branch "softly" to the branch you target (dev), commit with the same message. This way we get a single commit, we don't care about the history in this case. We are not asking that usually but I want to change this habit, using a simple technique. Thanks.

**Comment by dcinzona** [comment]
I wonder if this will work:
(got this from here: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history)
`git rebase -i HEAD~2`
`s`
Would that work?  I, too, am looking for an easy way to do this.

**Comment by dcinzona** [comment]
Or here is a better explanation: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by ryanmagoon** [comment]
Done

**Pull request merged**
