### PR TITLE
Improve build script to not fail when there is JS warning

### PR DESCRIPTION
**Pull request by aaronamm**
I have improve deploy.ps1 (Kudu App Services script) to 
- Not build fail when there is JS warning
- Auto build with yarn when there is yarn.lock file in a modules/themes folders
- Build support for MS build 16, so we can use a new C# syntax, e.g. tuple pattern matching

### CODE REVIEW

**Comment by Skrypt** [comment]
What you mean by JS warning? Because we run functional tests which should make the build fail if they don't pass.

**Comment by aaronamm** [comment]
@Skrypt  There are many times when we build node package/load a package, it send warning to a standard error and causes a build fail event though $exit code is 0.

Please check.
https://github.com/OrchardCMS/Orchard/blob/8156e23911f4492e24c5bb3d3c73bae29f672480/DeploymentUtility.psm1#L29

**Comment by aaronamm** [comment]
@Skrypt  I think I will deploy this project to Azure app service to make sure the build script work properly. 
I have tested with my project but it is good to test with a clean/initial state project.

I will update a website link to you after the deployment is successful.
Thanks.

**Comment by aaronamm** [comment]
@Skrypt  FYI, I think I have problem of wrong indention displayed in GitHub.
Especially when we have pipe |.
If you checkout this branch to your local machine, you will find that the indention is correct.

**Comment by Skrypt** [comment]
Ok, I will take some time to review the PR and analyze what you are trying to achieve. I don't think we build the assets through the CI because we commit the built assets in the repository. So, I assume you are somehow trying to automate the build of assets through the CI.

**Comment by Skrypt** [comment]
I'm sorry I just saw that this is for Orchard and not Orchard Core. I'm totally lost on this for Orchard I don't remember the details at all.

**Comment by aaronamm** [comment]
@Skrypt  That's okay. 
What I am trying to achieve is automate build a node project with yarn if there is a yarn.lock in themes or modules folders and improve the existing script for unnecessary &  call operation in script block.
It won't effect a project that build with. 

The script act the same as before except build with yarn for a module that has yarn.lock.

**Comment by sebastienros** [comment]
LGTM as long as it is tested by more than one person

**Comment by aaronamm** [comment]
@sebastienros Thank you so much. 
@Skrypt  I am working on deploy it Azure App Services, I will let you after I finish it ASAP.
FYI **LGTM**  is an acronym meaning "looks good to me".

**Comment by aaronamm** [comment]
Since we are here, I think it is good to update a nuget package from the latest version and make Kudu build script use it.
Therefore, I put a new commit to made PR.

**Comment by aaronamm** [comment]
@sebastienros  @Skrypt I 've already deployed this PR to Azure App Services. If this PR looks good to you, could you please merge it. 
Thanks.

Here is the deployment information.

URL:
https://orchard-pr.azurewebsites.net/

Database:
SQL Server compact

Receipt:
Blog

Additional configuration in Azure:
```
[
  {
    "name": "SCM_REPOSITORY_PATH",
    "value": "D:\\local\\repository",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_NODE_DEFAULT_VERSION",
    "value": "10.16.3",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_NPM_DEFAULT_VERSION",
    "value": "6.9.0",
    "slotSetting": false
  }
]
```

No error in frontend
image

No error in admin dashboard
image

**Comment by Skrypt** [comment]
We will probably triage this on Thursday. Unless @sebastienros has time to review it up untill then.

**Comment by aaronamm** [comment]
@Skrypt  Could you please help following up for this repository. 
Thanks.

**Comment by aaronamm** [comment]
@Skrypt @sebastienros  Any suggestion to this PR? I am happy to made some changes to get this PR merge.
Thanks.

**Comment by sebastienros** [comment]
Just noticed you have added NuGet.exe in the repository, you need to remove it.

**Comment by aaronamm** [comment]
@sebastienros  Nuget.exe has already exists in the project so what I did is only update it to the latest version.
This is because with the new nuget.exe version, I can control it to use a specific MS Build version.
Could you please explain the reason why I should remove it? I will remove it after I get a reason from you.
Thank you so much.

**Comment by aaronamm** [comment]
FYI @sebastienros 
image

**Comment by aaronamm** [comment]
@sebastienros  @Skrypt  could you please help me finish this PR?
Thank you so much.

**Pull request merged**
