### PR TITLE
It makes images recognizable in the admin even if they are white over a transparent background

### LINKED ISSUE #8328: MediaLibrary: PNG not visible if white over transparent bg
If we upload a white png with a transparent background, it results to be NOT 
recognizable in Media Library and in the Media Library Picker Field.
download

### PR DESCRIPTION
**Pull request by HermesSbicego-Laser**
fixes #8328, adding in the admin a white/grey squares background to containers of media of type "image"
Before
before-download

After
download

### CODE REVIEW

**Comment by sebastienros** [comment]
Why not use a static file instead so it doesn't have to be duplicated in the css?
It's not a huge issue, just a suggestion.

**Comment by HermesSbicego-Laser** [comment]
Intead of base64? It was just for consistency with other images used in that css... I will change it...

**Comment by sebastienros** [comment]
No it's ok then

**Comment by sebastienros** [comment]
No, it's ok then

**Pull request merged**
