### PR TITLE
#6410 Added NotifyType.Success 

### PR DESCRIPTION
**Pull request by SzymonSel**
and replaced most usages of `NotifyType.Information` with it. Added appropriate styles in css files.

Some minor fixes - wrong notification types.

### CODE REVIEW

**Comment by sebastienros** [comment]
Somehow this is a breaking change as you are using a new css class on the front end. No website will have this style defined if they upgrade, as you changed several front end information to success. It should target dev instead. Wait for more comments.

**Comment by SzymonSel** [comment]
Yup, I'm aware of that, but leaving the message-Information class referring to NotifyType.Success just didn't seem right.

**Comment by sebastienros** [comment]
So as I suggested (indirectly), please move to `dev`

**Comment by SzymonSel** [comment]
Will do

**Comment by sebastienros** [comment]
:watch:

**Comment by SzymonSel** [comment]
Noted!

**Comment by SzymonSel** [comment]
https://github.com/OrchardCMS/Orchard/pull/6634

**Pull request closed without merging**
