### PR TITLE
#6550: [1.10.x] no required on client side if default value is set (TextField)

### PR DESCRIPTION
**Pull request by jtkech**
Fixes partially #6550.

Re-done to target 1.10.x. Other fields will come, i'll try to group them but i need to test again all options and each field has its special cases.

- If required and a default value is set, then no required on client side, but still with the required class to have the red star, and still required on server side.

- **Special case**: The default value is tokenized in a 2nd driver and the result can be empty. So, the required checking is also done in the 2nd driver. Because, if the default has a value, it has not been done in the 1st driver.

Best

### CODE REVIEW

**Comment by jtkech** [comment]
I lost my changes after a bad squash / revert. I'll re-do it asap

**Comment by jtkech** [comment]
@sebastienros Added specflows.

**Comment by jtkech** [comment]
@sebastienros 

Not urgent at all for me, it's just for infos because it's the last one of the serie where i've added specflows.

Note: Other fields are already commited to 1.10.x (and recently merged in dev).

Best.

**Comment by sebastienros** [comment]
I am merging this one, but the goal of squash is to get a single commit, not an extra one named `squash` ;)

**Comment by jtkech** [comment]
Ok, sorry.

**Pull request merged**
