### PR TITLE
Improve Orchard.Layouts UX

### PR DESCRIPTION
**Pull request by HermesSbicego-Laser**
Improve UX of the LayoutPart Editor

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you share some screenshots before/after to understand the changes?

**Review by sebastienros — APPROVED** [review]

**Comment by HermesSbicego-Laser** [comment]
@sebastienros 
**Before**
before - dev-layouts-New-Page (big toolbar)
before - dev-layouts-New-Page (big editor)

After
after - dev-layouts-New-Page (big toolbar)
after - dev-layouts-New-Page (big editor)

**Comment by BenedekFarkas** [comment]
@HermesSbicego-Laser I'm working on #8773 now and there were some merge conflicts between 1.10.x and dev regarding some of the client-side assets. Recompilation works fine (which I find a positive surprise considering how outdated the compilation pipeline is) with Node v7 in the Task Runner Explorer.

I ran it first just on 1.10.x to validate the output and got the following results:

- 233 js/css files were updated across various modules, but just their `sourceMappingURL`s.
- In Orchard.Resources, a few files were updated functionality-wise, but everything still seems to be working fine there.
- In Orchard.Layouts, which is affected by this PR, the LayoutEditor style and script are both updated functionality-wise.

Layouts still works great, but the layout editor toolbox became very restricted in terms of its height [due to this specific line](https://github.com/OrchardCMS/Orchard/pull/8721/files#diff-d2d5eeb9b972715df8dcd5df4a098d949a10b2074b169b8e2789c29652525224R32):
image

Can you please check what happens if you do a full recompilation of client-side assets with the `rebuild` task? I've committed the output from my local testing to the `issue/8773-1.10.x` branch (13bbb43e3580ce830fab9deecec1cacbaacdf849) and then a rework of the sticky behavior (c420676ba03c6f431a44724319dc590259575281).
image

**Comment by MatteoPiovanelli** [comment]
@BenedekFarkas Could you please clarify what do you need us to check? What branch do you need us to try and rebuild the assets on?

**Comment by BenedekFarkas** [comment]
I've moved on from this for a while, so I recompiled everything and resolved the issues already, but the issue was present on this PR's branch, as well as 1.10.x and dev.

**Pull request merged**
