### PR TITLE
Possibility of exporting individual Form Submissions

### LINKED ISSUE #7486: Possibility of exporting individual Form Submissions
The current implementation of Import/Export for Dynamic Forms exports all form submissions. It would be awesome if it allowed exporting submissions of individual forms just like we have an editor available under "Content and Content Definition" which allows selecting individual content types for export.

### PR DESCRIPTION
**Pull request by hannan-azam**
Fixes #7486

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you do a demo on Tuesday?

**Comment by sebastienros** [comment]
You missed the meeting, postponing to next one.

**Comment by hannan-azam** [comment]
@sebastienros Due to timezone issues im not able to join the meeting. I have created this video showing the working of this PR. Please let me know if you need something else.

https://sendvid.com/ihtqohkq

**Comment by sebastienros** [comment]
We watched the video and the only comment is to have the same style for the table (spacing issues) as there is in the Content section which is just under.
Thanks

**Comment by sebastienros** [comment]
Can you paste a screenshot of the form here? The css change doesn't look like what we suggested.

**Comment by hannan-azam** [comment]
@sebastienros We have kept all styles same as of content section. The table dimensions look ok. Are you talking about the position of the checkboxes and that those should align with the checkboxes in content section?
If it is so we will have to specify a custom width to the first column in both tables.
dynamic forms

**Pull request merged**
