### PR TITLE
Feature/admin theme Update EditPlacement.cshtml 

### PR DESCRIPTION
**Pull request by ramiassi**
If the script snippet is not located in the footer then jQuery will not be recognized.

### CODE REVIEW

**Comment by Skrypt** [comment]
That's the kind of thing that will require to be set on the footer if some of your javascript functions are not executed on document.ready(). I prefer having it on top to force me to do so.

**Comment by sfmskywalker** [comment]
Wasn't the issue that the `$` symbol was not available in the first place? If not, then you're right.

**Comment by Skrypt** [comment]
Not supposed to. I think most of main modules are using JQuery in there. Lists whas working and it's using some JQuery plugin. So maybe the problem is that the customizations that @ramiassi did on his own custom modules would need to use document.ready().

**Comment by sfmskywalker** [comment]
That's a good observation. I'll look into this in more detail and see what needs to be done. Thanks for being so vigilant Jasmin, appreciate it.

**Pull request merged**
