### PR TITLE
fixing split extension method for #5348

### PR DESCRIPTION
**Pull request by thekaveman**
c337948 is causing a compiler error in 1.9.x

### CODE REVIEW

**Comment by Skrypt** [comment]
faster than the pitcher :)

**Comment by thekaveman** [comment]
:smile:

**Comment by netwavebe** [comment]
Yes, this should fix the problem I mentioned in https://github.com/OrchardCMS/Orchard/issues/5348. Please merge!

Thanks for the follow-up, Kegan!

**Comment by thekaveman** [comment]
Fixed in another commit from @BenedekFarkas

**Pull request closed without merging**
